#version 460

#extension GL_ARB_shading_language_include : require

#include "UnityFunctions.glsl"
layout (set = 0, binding = 0) uniform sampler2D srcLowTexture;
layout (set = 0, binding = 1, rgba32f) uniform image2D srcHighTexture;
layout (set = 0, binding = 2) uniform writeonly image2D dstTexture;

layout (set = 0, binding = 3) uniform Constants{
    vec2 lowSize;
    vec2 highSize;
    float scatter; // 0.68
} constants;

layout(local_size_x = 8, local_size_y = 8) in;
void main()
{
    vec2 lowSizeZW = vec2(1.0) / constants.lowSize;
    vec2 texelSizeZW = vec2(1.0) / constants.highSize;

    PositionInputs posInputs = GetPositionInput(vec2(gl_GlobalInvocationID.xy), texelSizeZW, uvec2(8));

    vec2 uv = ClampAndScaleUVPostProcessTexture(posInputs.positionNDC, lowSizeZW, 1.0f);

    vec3 highRes = imageLoad(srcHighTexture, ivec2(clamp(posInputs.positionSS, uvec2(0), constants.highSize.xy - 1))).xyz;

    vec2 maxCoord = 1.0f - texelSizeZW;
    vec3 lowRes = SampleTexture2DBicubic(srcLowTexture, uv, vec4(constants.lowSize, lowSizeZW), maxCoord).xyz;


    vec3 upSampleOut = mix(highRes, lowRes, constants.scatter);

    // Guard bands
    upSampleOut *= all(gl_GlobalInvocationID.xy,uvec2(constants.highSize.xy));

    imageStore(dstTexture,ivec2(gl_GlobalInvocationID.xy),vec4(upSampleOut, 1.0));
}