#version 460

#extension GL_ARB_shading_language_include : require

#include "UnityFunctions.glsl"
layout (set = 0, binding = 0) uniform sampler2D srcTexture;
layout (set = 0, binding = 1) uniform writeonly image2D dstTexture;

layout (set = 0, binding = 2)  uniform Constants{
    vec2 srcResolution; // screen size
    vec2 outputImageSize; // texel size
    // vec4 screenSize; // main colour attachment screen size (srcTexture) raw pixels = xy | 1/raw pixels = zw
    // vec4 postProcessScreenSize; // main colour attachment screen size (srcTexture) raw pixels = xy | 1/raw pixels = zw
    // vec4 postProcessScale; // 1, 1, 1, 1
    vec4 bloomThreshold; // 0.0, -1.0*10-5, 0.00002, 25000.0
} constants;

vec2 ClampAndScaleUVForBilinearPostProcessTexture(vec2 uv){
    //return ClampAndScaleUV(uv,_screenSize.zw,0.5,postProcessScale.xy);
    return ClampAndScaleUV(uv, vec2(1.0)/constants.srcResolution, 0.5, vec2(1));
}

float Luminance(vec3 linearRgb)
{
    return dot(linearRgb, vec3(0.2126729, 0.7151522, 0.0721750));
}

vec3 BilinearSample(vec2 uv, vec2 offset, out float weight)
{
    //vec3 c = texture(srcTexture, s_linear_clamp_sampler, ClampAndScaleUVForBilinearPostProcessTexture(uv + offset * _PostProcessScreenSize.zw), 0.0).rgb;
    vec3 c = texture(srcTexture, ClampAndScaleUVForBilinearPostProcessTexture(uv + offset * (vec2(1.0)/constants.srcResolution))).rgb;

    //c.xyz = QuadraticThreshold(c.xyz, _BloomThreshold.x, _BloomThreshold.yzw);
    c.xyz = QuadraticThreshold(c.xyz, constants.bloomThreshold.x, constants.bloomThreshold.yzw);

    weight = 1.0 / (Luminance(c.xyz) + 1.0);
    return c.xyz;
}

vec3 PartialAverage(vec3 c0, vec3 c1, vec3 c2, vec3 c3, float w0, float w1, float w2, float w3)
{
    return (c0*w0 + c1*w1 + c2*w2 + c3*w3) / (w0 + w1 + w2 + w3);
}


layout(local_size_x = 8, local_size_y = 8) in;
void main()
{
    vec2 texelSizeZW = vec2(1.0) / constants.outputImageSize;
    PositionInputs posInputs = GetPositionInput(vec2(gl_GlobalInvocationID.xy), texelSizeZW, uvec2(8, 8));
    vec2 uv = posInputs.positionNDC;

    // "Post-Processing in CoD Advanced Warfare" [Jimenez14]
    float wA, wB, wC, wD, wE, wF, wG, wH, wI, wJ, wK, wL, wM;
    vec3 A = BilinearSample(uv, vec2(-1.0, -1.0), wA);
    vec3 B = BilinearSample(uv, vec2( 0.0, -1.0), wB);
    vec3 C = BilinearSample(uv, vec2( 1.0, -1.0), wC);
    vec3 D = BilinearSample(uv, vec2(-0.5, -0.5), wD);
    vec3 E = BilinearSample(uv, vec2( 0.5, -0.5), wE);
    vec3 F = BilinearSample(uv, vec2(-1.0,  0.0), wF);
    vec3 G = BilinearSample(uv, vec2( 0.0,  0.0), wG);
    vec3 H = BilinearSample(uv, vec2( 1.0,  0.0), wH);
    vec3 I = BilinearSample(uv, vec2(-0.5,  0.5), wI);
    vec3 J = BilinearSample(uv, vec2( 0.5,  0.5), wJ);
    vec3 K = BilinearSample(uv, vec2(-1.0,  1.0), wK);
    vec3 L = BilinearSample(uv, vec2( 0.0,  1.0), wL);
    vec3 M = BilinearSample(uv, vec2( 1.0,  1.0), wM);

    vec3 prefilterOut = vec3(0);
    prefilterOut += PartialAverage(D, E, I, J, wD, wE, wI, wJ) * 0.5;
    prefilterOut += PartialAverage(A, B, F, G, wA, wB, wF, wG) * 0.125;
    prefilterOut += PartialAverage(B, C, G, H, wB, wC, wG, wH) * 0.125;
    prefilterOut += PartialAverage(F, G, K, L, wF, wG, wK, wL) * 0.125;
    prefilterOut += PartialAverage(G, H, L, M, wG, wH, wL, wM) * 0.125;


    // Guard bands
    prefilterOut *= all(gl_GlobalInvocationID.xy, uvec2(constants.outputImageSize));
    
    imageStore(dstTexture, ivec2(posInputs.positionSS), vec4(prefilterOut,1.0));

}