#version 460

#extension GL_ARB_shading_language_include : require

#include "../compute_texture_functions.glsl"
#include "UnityFunctions.glsl"
layout (set = 0, binding = 0) uniform sampler2D srcTexture;
layout (set = 0, binding = 1) uniform writeonly image2D dstTexture;

layout (push_constant)  uniform Constants{
    vec4 outputImageSize; // texel size
    vec4 srcResolution; // screen size
    // vec4 screenSize; // main colour attachment screen size (srcTexture) raw pixels = xy | 1/raw pixels = zw
    // vec4 postProcessScreenSize; // main colour attachment screen size (srcTexture) raw pixels = xy | 1/raw pixels = zw
    // vec4 postProcessScale; // 1, 1, 1, 1
    vec4 bloomThreshold; // 0.0, -1.0*10-5, 0.00002, 25000.0
} constants;

float Luminance(vec3 linearRgb)
{
    return dot(linearRgb, vec3(0.2126729, 0.7151522, 0.0721750));
}

vec3 BilinearSample(vec2 uv, vec2 offset, out float weight)
{
    //vec3 c = texture(srcTexture, s_linear_clamp_sampler, ClampAndScaleUVForBilinearPostProcessTexture(uv + offset * _PostProcessScreenSize.zw), 0.0).rgb;
    vec3 c = texture(srcTexture, ClampAndScaleUVForBilinearPostProcessTexture(uv + offset * (constants.srcResolution.zw), constants.srcResolution.zw)).xyz;

    //c.xyz = QuadraticThreshold(c.xyz, _BloomThreshold.x, _BloomThreshold.yzw);
    c.xyz = QuadraticThreshold(c.xyz, constants.bloomThreshold.x, constants.bloomThreshold.yzw);

    weight = 1.0 / (Luminance(c.xyz) + 1.0);
    return c.xyz;
}

vec3 PartialAverage(vec3 c0, vec3 c1, vec3 c2, vec3 c3, float w0, float w1, float w2, float w3)
{
    return (c0*w0 + c1*w1 + c2*w2 + c3*w3) / (w0 + w1 + w2 + w3);
}


layout(local_size_x = 8, local_size_y = 8) in;
void main()
{
    PositionInputs posInputs = GetPositionInput(vec2(gl_GlobalInvocationID.xy), constants.outputImageSize.zw, uvec2(8, 8));
    vec2 uv = posInputs.positionNDC;
	const vec2 kTaps [] = {
		vec2 (0.0, 0.0),
		vec2 (0.9, - 0.4),
		vec2 (- 0.9, 0.4),
		vec2 (0.4, 0.9),
		vec2 (- 0.4, - 0.9)
	};
	float w0, w1, w2, w3, w4;
	vec3 color0 = BilinearSample (uv, kTaps [0], w0);
	vec3 color1 = BilinearSample (uv, kTaps [1], w1);
	vec3 color2 = BilinearSample (uv, kTaps [2], w2);
	vec3 color3 = BilinearSample (uv, kTaps [3], w3);
	vec3 color4 = BilinearSample (uv, kTaps [4], w4);
	float wSum = w0 + w1 + w2 + w3 + w4;
	color0 *= w0;
	color1 *= w1;
	color2 *= w2;
	color3 *= w3;
	color4 *= w4;
	vec3 acc = color0 + color1 + color2 + color3 + color4;
	vec3 prefilterOut = acc / wSum;

    // Guard bands
    prefilterOut *= all(gl_GlobalInvocationID.xy, uvec2(constants.outputImageSize));
    
    imageStore(dstTexture, ivec2(posInputs.positionSS), vec4(prefilterOut,1.0));

}