#version 460
#extension GL_ARB_shading_language_include : require
#include "../../common_structures.glsl"
#include "../compute_texture_functions.glsl"

layout(set = 0, binding = 0) readonly buffer SSAOKernels {
	vec4 values[];
} ssaoKernels;

layout(set = 0,binding = 1) readonly buffer CameraDatas {
	CameraData values[];
} cameraData;

layout (set = 0, binding = 2) uniform sampler2D ssaoNoise;
layout (set = 0, binding = 3) uniform sampler2D mainDepth;
layout (set = 1, binding = 0) uniform sampler2D g_PositionIn;
layout (set = 1, binding = 1) uniform sampler2D g_NormalsIn;
layout (set = 1, binding = 2, r8) uniform writeonly image2D ssao_Source;

layout(push_constant) uniform Constants{
    vec4 srcImageSize;
    vec4 outputImageSize;
    vec2 noiseScale;
    vec2 renderScale;
    float radius;
    float bias;
	uint cameraIndex;
    int kernelSize;
} constants;

float glLinearDepth(float depth){
    float near = cameraData.values[constants.cameraIndex].nearPlane;
    float far = cameraData.values[constants.cameraIndex].farPlane;
    float ndc = depth * 2.0 - 1.0;
    float linearDepth = (2.0 * near * far) / (far + near - ndc * (far - near));
    return linearDepth;
}

layout(local_size_x = 8, local_size_y = 8) in;
void main(){
    PositionInputs posInputs = GetPositionInput(vec2(gl_GlobalInvocationID.xy), constants.outputImageSize.zw, uvec2(8, 8));

    vec2 uv = posInputs.positionNDC.xy;


    vec4 positionWorld = texture(g_PositionIn, ClampAndScaleUVForBilinear(uv, constants.srcImageSize.zw,constants.renderScale)).rgba;
    // transform world post to view pos
    vec3 viewPos = (cameraData.values[constants.cameraIndex].viewMatrix * vec4(positionWorld.xyz,1.0)).xyz;
    // src normal vector
    vec3 N = normalize(texture(g_NormalsIn, ClampAndScaleUVForBilinear(uv, constants.srcImageSize.zw,constants.renderScale)).rgb);


    vec3 randomVec = normalize(vec3(texture(ssaoNoise, uv*constants.noiseScale).xy,0));
    vec3 tangent = normalize(randomVec - N * dot(randomVec, N));
    vec3 bitangent = cross(N,  tangent );
    mat3 TBN = mat3(tangent, bitangent, N);
    
    float occlusion = 0.0;    
    for(int i = 0; i < constants.kernelSize; ++i){

        // get sample position
        vec3 samplePos = TBN * ssaoKernels.values[i].xyz; // from tangent to view-space
        samplePos = viewPos + samplePos * constants.radius;

        vec4 offset = vec4(samplePos, 1.0);
        offset = cameraData.values[constants.cameraIndex].projectionMatrix * offset;    // from view to clip-space
        offset.xyz /= offset.w;               // perspective divide
        offset.xyz = offset.xyz * 0.5 + 0.5; // transform to range 0.0 - 1.0
        
        float sampleDepth = -glLinearDepth(texture(mainDepth, ClampAndScaleUVForBilinear(vec2(offset.x,1-offset.y), constants.srcImageSize.zw,constants.renderScale)).r);
        //float sampleDepth = -texture(g_PositionIn, vec2(offset.x,1-offset.y)).w;

        float rangeCheck = smoothstep(0.0, 1.0, constants.radius / abs(viewPos.z - sampleDepth));
        occlusion += (sampleDepth >= samplePos.z + constants.bias ? 1.0 : 0.0) * rangeCheck;  
    }

    occlusion = 1.0 - (occlusion / constants.kernelSize);
    //ssaoOut = occlusion;
    imageStore(ssao_Source, ivec2(posInputs.positionSS), vec4(occlusion));
}