#version 460

struct ObjectMatrices {
	mat4 modelMatrix; // project * view * model
	mat4 normalMatrix;
};

struct ObjectBounds {
	vec4 bMin;
	vec4 bMax;
};

struct DrawCommand {
	uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

struct DrawCullData {
	float P00, P11, znear, zfar; // symmetric projection parameters
	float frustum[4]; // data for left/right/top/bottom frustum planes
	uint drawCount;
	int cullingEnabled;
	int distCull;
};

struct PointLight {
	vec4 position; // ignore w
	vec4 colour; // w is intensity
};

layout(set = 0, binding = 0) uniform GlobalUbo {
	mat4 projectionMatrix;
	mat4 viewMatrix;
	mat4 inverseViewMatrix;
	vec4 ambientLightColour;
	int numLights;
	PointLight pointLights[10];
} ubo;

layout(std140, set = 1, binding = 0) readonly buffer ObjectMatricesBuffer {
	ObjectMatrices matrices[];
} matricesBuffer;

layout(std140, set = 1, binding = 1) readonly buffer ObjectBoundsBuffer {
	ObjectBounds bounds[];
} boundsBuffer;

layout(set = 1, binding = 2)  buffer InstanceBuffer {
	DrawCommand Draws[];
} drawBuffer;

layout(push_constant) uniform  constants{   
   DrawCullData cullData;
};

bool IsVisible(uint objectIndex)
{
	mat4 modelMat = matricesBuffer.matrices[objectIndex].modelMatrix;
	vec3 center = vec3(modelMat[0][3],modelMat[1][3],modelMat[2][3]);
	
	center = (ubo.viewMatrix * vec4(center,1.0)).xyz;

	float radius = boundsBuffer.bounds[objectIndex].bMin.w;

	bool visible = true;

	// the left/top/right/bottom plane culling utilizes frustum symmetry to cull against two planes at the same time
	visible = visible && center.z * cullData.frustum[1] - abs(center.x) * cullData.frustum[0] > -radius;
	visible = visible && center.z * cullData.frustum[3] - abs(center.y) * cullData.frustum[2] > -radius;

	if(cullData.distCull != 0)
	{// the near/far plane culling uses camera space Z directly
		visible = visible && center.z + radius > cullData.znear && center.z - radius < cullData.zfar;
	}

	return visible;
}

layout(local_size_x = 256) in;
void main() {
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		bool visible = false;
			visible = IsVisible(gID);
		if(visible)
		{
			uint countIndex = atomicAdd(drawBuffer.Draws[gID].instanceCount,1);
		}
	}
}