<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SDL_Vulkan_CS</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <StartupObject>SDL_Vulkan_CS.BasicTest</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alimer.Bindings.SDL" Version="3.9.4" />
    <PackageReference Include="Vortice.Vulkan" Version="1.9.9" />
  </ItemGroup>

</Project>
