#version 460

struct ObjectBounds {
	vec4 bMin;
	vec4 bMax;
};

struct DrawCommand {
	uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

layout(std140, set = 0, binding = 0) readonly buffer ObjectBoundsBuffer {
	ObjectBounds bounds[];
} boundsBuffer;

layout(set = 0, binding = 1) buffer InstanceBuffer {
	DrawCommand Draws[];
} drawBuffer;

layout(push_constant) uniform  constants{
	vec4 frustum[6]; // data for left/right/top/bottom frustum planes
	uint drawCount;
	int cullingEnabled;
	int distCull;
	int depthCulling;
} cullData;

bool IsVisible(uint objectIndex)
{
	ObjectBounds bounds = boundsBuffer.bounds[objectIndex];

	vec4 bmin = bounds.bMin;
	float cullOveride = bmin.w;
	if(cullOveride > 0.5 && cullOveride < 2) return true;

	vec4 bmax = bounds.bMax;
	bmin.w = 1;
	bmax.w = 1;
	int planeCount = cullData.distCull == 1 ? 6 : 4;
	for (int i = 0; i < 6; i++)
	{
	    vec4 g = cullData.frustum[i];
	    bool visible =
		dot(g, bmin) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, bmax) < 0.0;

	    if (visible)
	    {
	        return false;
	    }
	}
	return true;
}

layout(local_size_x = 256) in;
void main()
{
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		bool visible = IsVisible(gID);
		if(visible || cullData.cullingEnabled == 0)
		{
			drawBuffer.Draws[gID].instanceCount = 1;
		}
		else
		{
			drawBuffer.Draws[gID].instanceCount = 0;
		}
	}
}