#version 460

struct ObjectBounds {
	vec4 bMin;
	vec4 bMax;
};

struct DrawCommand {
	uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

layout(std140, set = 0, binding = 0) readonly buffer ObjectBoundsBuffer {
	ObjectBounds bounds[];
} boundsBuffer;

layout(set = 0, binding = 1) buffer InstanceBuffer {
	DrawCommand Draws[];
} drawBuffer;

layout(push_constant) uniform  constants{   
	mat4 viewMatrix;
	float P00, P11, znear, zfar; // symmetric projection parameters
	float frustum[4]; // data for left/right/top/bottom frustum planes
	uint drawCount;
	int cullingEnabled;
	int distCull;
} cullData;

bool IsVisible(uint objectIndex)
{
	ObjectBounds bounds = boundsBuffer.bounds[objectIndex];

	vec3 extents = (bounds.bMax.xyz - bounds.bMin.xyz) * 0.5;

	vec3 center = bounds.bMin.xyz + extents;
	
    center = (cullData.viewMatrix * vec4(center, 1)).xyz;

	float radius = bounds.bMin.w;

	bool visible = true;

	// the left/top/right/bottom plane culling utilizes frustum symmetry to cull against two planes at the same time
	visible = visible && center.z * cullData.frustum[1] - abs(center.x) * cullData.frustum[0] > -radius;
	visible = visible && center.z * cullData.frustum[3] - abs(center.y) * cullData.frustum[2] > -radius;

	if(cullData.distCull != 0)	{
		// the near/far plane culling uses camera space Z directly
		visible = visible && abs(center.z) + radius > cullData.znear && abs(center.z) - radius < cullData.zfar;
	}

	return visible;
}

layout(local_size_x = 256) in;
void main()
{
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		bool visible = IsVisible(gID);
		if(visible || cullData.cullingEnabled == 0)
		{
			drawBuffer.Draws[gID].instanceCount = 1;
		}
		else
		{
			drawBuffer.Draws[gID].instanceCount = 0;
		}
	}
}