#version 460

struct ObjectBounds {
	vec4 bMin;
	vec4 bMax;
};

struct DrawCommand {
	uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

layout(std140, set = 0, binding = 0) readonly buffer ObjectBoundsBuffer {
	ObjectBounds bounds[];
} boundsBuffer;

layout(set = 0, binding = 1) buffer InstanceBuffer {
	DrawCommand Draws[];
} drawBuffer;

layout(set = 0, binding = 2) uniform sampler2D depthPyramid;

layout(push_constant) uniform  constants{
	vec4 frustum[6]; // data for left/right/top/bottom frustum planes
	float zNear;
	float P00;
	float P11;
	vec2 pyramid;
	uint drawCount;
	int cullingEnabled;
	int distCull;
	int depthCulling;
} cullData;

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
bool projectSphere(vec3 C, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (-C.z < r + znear)
		return false;

	vec2 cx = vec2(-C.x,C.z);
	vec2 vx = vec2(sqrt(dot(cx, cx) - r * r), r);
	vec2 minx = mat2(vx.x, vx.y, -vx.y, vx.x) * cx;
	vec2 maxx = mat2(vx.x, -vx.y, vx.y, vx.x) * cx;

	vec2 cy = C.yz;
	vec2 vy = vec2(sqrt(dot(cy, cy) - r * r), r);
	vec2 miny = mat2(vy.x, vy.y, -vy.y, vy.x) * cy;
	vec2 maxy = mat2(vy.x, -vy.y, vy.y, vy.x) * cy;

	aabb = vec4(minx.x / minx.y * P00, miny.x / miny.y * P11, maxx.x / maxx.y * P00, maxy.x / maxy.y * P11);
	aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f); // clip space -> uv space

	return true;
}

bool IsVisible(uint objectIndex)
{
	ObjectBounds bounds = boundsBuffer.bounds[objectIndex];

	vec4 bmin = bounds.bMin;
	float cullOveride = bmin.w;
	if(cullOveride > 0.5 && cullOveride < 2) return true;

	vec4 bmax = bounds.bMax;
	bmin.w = 1;
	bmax.w = 1;
	int planeCount = cullData.distCull == 1 ? 6 : 4;
	for (int i = 0; i < 6; i++)
	{
	    vec4 g = cullData.frustum[i];
	    bool visible =
		dot(g, bmin) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, bmax) < 0.0;

	    if (visible)
	    {
	        return false;
	    }
	}

    if(cullData.depthCulling != 0)
	{
		vec3 center =  bmin.xyz + ((bmax.xyz - bmin.xyz) * 0.5);
		//flip Y because we access depth texture that way
		//center.z *= -1.0;
		
		float radius = distance(bmin.xyz,bmax.xyz)*0.5;
		
		vec4 aabb;
		if(projectSphere(center, radius, cullData.zNear, cullData.P00, cullData.P11, aabb)){
			float width = (aabb.z - aabb.x) * cullData.pyramid.x;
			float height = (aabb.w - aabb.y) * cullData.pyramid.y;

			float level = floor(log2(max(width, height)));

			float depth = textureLod(depthPyramid, (aabb.xy + aabb.zw) * 0.5, level).x;
			float depthSphere =cullData.zNear / (center.z - radius);

		
			return depthSphere >= depth;
		}
	}

	return true;
}

layout(local_size_x = 256) in;
void main()
{
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		bool visible = IsVisible(gID);
		if(visible || cullData.cullingEnabled == 0)
		{
			drawBuffer.Draws[gID].instanceCount = 1;
		}
		else
		{
			drawBuffer.Draws[gID].instanceCount = 0;
		}
	}
}