#version 460

// information about the main buffer defining what threads should run/abort
layout(set = 0, binding = 0) uniform ComputeShaderParameters{
	uint bufferLength;
	uint width;
	uint height;
	uint depth;
} params;


// vertex buffer to operate on (direct mesh buffer) Only read from here.
layout(std430,set = 0, binding = 1) readonly buffer VertexBuffer {
    float values[];
} vertices;

// index buffer to operate on (direct mesh buffer) Only read from here.
layout(std430,set = 0, binding = 2) readonly buffer IndexBuffer {
    uint values[];
} indices;

// sizeof vertex buffer * 3 unormalized normals for each vertex expressed as ints to because atomic add
layout(std430,set = 0, binding = 3) writeonly buffer NormalBuffer {
    int values[];
} normals;

// this buffer is added to the index buffer to get the true vertex index
layout(std430,set = 0, binding = 4) readonly buffer IndexOffsets{
	uint values[];
} indexOffsets;

// fucked up float to int conversion magic number (2^16/2)
const float QUANTIIZE_FACTOR = 32768.0;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
	if(params.width <= gl_GlobalInvocationID.x || params.height <= gl_GlobalInvocationID.y){
	 	return; 
	}

	// iterating 1 triangle per thread, triangle made up of 3 indices
	uint valuesIndex = (gl_GlobalInvocationID.y * params.width + gl_GlobalInvocationID.x) * 3;
	if(valuesIndex + 2 > params.bufferLength){
		return;
	}
	uint indexA = (indexOffsets.values[valuesIndex] + indices.values[valuesIndex]) * 3;
	uint indexB = (indexOffsets.values[valuesIndex + 1] + indices.values[valuesIndex + 1]) * 3;
	uint indexC = (indexOffsets.values[valuesIndex + 2] + indices.values[valuesIndex + 2]) * 3;
	// to write into the normal buffer multiply indices by 3 again for each component.

	vec3 posA = vec3(vertices.values[indexA], vertices.values[indexA + 1], vertices.values[indexA + 2]);
	
	vec3 posB = vec3(vertices.values[indexB], vertices.values[indexB + 1], vertices.values[indexB + 2]);

	vec3 posC = vec3(vertices.values[indexC], vertices.values[indexC + 1], vertices.values[indexC + 2]);

	// compute face normal, remap the vec3 as an int vec3 for atomic add
	ivec3 faceNormal = ivec3(normalize(cross(posB - posA, posC - posA)) * QUANTIIZE_FACTOR);
	atomicAdd(normals.values[indexA],faceNormal.x);
	atomicAdd(normals.values[indexA + 1], faceNormal.y);
	atomicAdd(normals.values[indexA + 2], faceNormal.z);
	atomicAdd(normals.values[indexB], faceNormal.x);
	atomicAdd(normals.values[indexB + 1], faceNormal.y);
	atomicAdd(normals.values[indexB + 2], faceNormal.z);
	atomicAdd(normals.values[indexC], faceNormal.x);
	atomicAdd(normals.values[indexC + 1], faceNormal.y);
	atomicAdd(normals.values[indexC + 2], faceNormal.z);

}