using BCnEncoder.Encoder;
using BCnEncoder.Shared;
using BCnEncoder.Shared.ImageFiles;
using System;
using Vortice.Vulkan;

namespace VECS
{
    internal static class TextureFormatConverter
    {
        public static bool IsCompressedFormat(this VkFormat format)
        {
            return format switch
            {
                VkFormat.Bc1RgbUnormBlock => true,
                VkFormat.Bc1RgbaUnormBlock => true,
                VkFormat.Bc2UnormBlock => true,
                VkFormat.Bc3UnormBlock => true,
                VkFormat.Bc4UnormBlock => true,
                VkFormat.Bc5UnormBlock => true,
                VkFormat.Bc6hUfloatBlock => true,
                VkFormat.Bc6hSfloatBlock => true,
                VkFormat.Bc7UnormBlock => true,
                _ => false
            };
        }

        public static VkFormat GetUncompressedFormat(this VkFormat format)
        {
            return format switch
            {
                VkFormat.Bc1RgbUnormBlock => VkFormat.R8G8B8Unorm,
                VkFormat.Bc1RgbaUnormBlock => VkFormat.R8G8B8A8Unorm,
                VkFormat.Bc2UnormBlock => VkFormat.R8G8B8A8Unorm,
                VkFormat.Bc3UnormBlock => VkFormat.R8G8B8A8Unorm,
                VkFormat.Bc4UnormBlock => VkFormat.R8Unorm,
                VkFormat.Bc5UnormBlock => VkFormat.R8G8Unorm,
                VkFormat.Bc6hUfloatBlock => VkFormat.R8G8B8Unorm,
                VkFormat.Bc6hSfloatBlock => VkFormat.R8G8B8Snorm,
                VkFormat.Bc7UnormBlock => VkFormat.R8G8B8A8Unorm,
                _ => format
            };
        }

        public static VkFormat GetVkFormat(this CompressionFormat compressionFormat)
        {
            return compressionFormat switch
            {
                CompressionFormat.R => VkFormat.R8Unorm,
                CompressionFormat.Rg => VkFormat.R8G8Unorm,
                CompressionFormat.Rgb => VkFormat.R8G8B8Unorm,
                CompressionFormat.Rgba => VkFormat.R8G8B8A8Unorm,
                CompressionFormat.Bgra => VkFormat.B8G8R8A8Unorm,
                CompressionFormat.Bc1 => VkFormat.Bc1RgbUnormBlock,
                CompressionFormat.Bc1WithAlpha => VkFormat.Bc1RgbaUnormBlock,
                CompressionFormat.Bc2 => VkFormat.Bc2UnormBlock,
                CompressionFormat.Bc3 => VkFormat.Bc3UnormBlock,
                CompressionFormat.Bc4 => VkFormat.Bc4UnormBlock,
                CompressionFormat.Bc5 => VkFormat.Bc5UnormBlock,
                CompressionFormat.Bc6U => VkFormat.Bc6hUfloatBlock,
                CompressionFormat.Bc6S => VkFormat.Bc6hSfloatBlock,
                CompressionFormat.Bc7 => VkFormat.Bc7UnormBlock,
                _ => throw new NotImplementedException(string.Format("Texture format {0} not supported by vulkan!", compressionFormat))

            };
        }

        public static CompressionFormat GetCompressionFormat(this VkFormat vkFormat)
        {
            return vkFormat switch
            {
                VkFormat.R8Unorm => CompressionFormat.R,
                VkFormat.R8G8Unorm => CompressionFormat.Rg,
                VkFormat.R8G8B8Unorm => CompressionFormat.Rgb,
                VkFormat.R8G8B8A8Unorm => CompressionFormat.Rgba,
                VkFormat.B8G8R8A8Unorm => CompressionFormat.Bgra,
                VkFormat.Bc1RgbUnormBlock => CompressionFormat.Bc1,
                VkFormat.Bc1RgbaUnormBlock => CompressionFormat.Bc1WithAlpha,
                VkFormat.Bc2UnormBlock => CompressionFormat.Bc2,
                VkFormat.Bc3UnormBlock => CompressionFormat.Bc3,
                VkFormat.Bc4UnormBlock => CompressionFormat.Bc4,
                VkFormat.Bc5UnormBlock => CompressionFormat.Bc5,
                VkFormat.Bc6hUfloatBlock => CompressionFormat.Bc6U,
                VkFormat.Bc6hSfloatBlock => CompressionFormat.Bc6S,
                VkFormat.Bc7UnormBlock => CompressionFormat.Bc7,
                _ => throw new NotImplementedException(string.Format("Texture format {0} not supported by vulkan!", vkFormat))
            };
        }

        public static VkFormat GetVkFormat(this GlInternalFormat glInternalFormat)
        {
            return glInternalFormat switch
            {
                // Colour
                GlInternalFormat.GlRgba4 => VkFormat.R4G4B4A4UnormPack16,
                GlInternalFormat.GlRgb5 => throw new NotImplementedException("Format not supported by Vulkan"),
                GlInternalFormat.GlRgb565 => VkFormat.R5G6B5UnormPack16,
                GlInternalFormat.GlRgba8 => VkFormat.R8G8B8A8Unorm,
                GlInternalFormat.GlRgb5A1 => VkFormat.R5G5B5A1UnormPack16,
                GlInternalFormat.GlRgba16 => VkFormat.R16G16B16A16Unorm,
                GlInternalFormat.GlR8 => VkFormat.R8Unorm,
                GlInternalFormat.GlRg8 => VkFormat.R8G8Unorm,
                GlInternalFormat.GlRg16 => VkFormat.R16G16Unorm,
                GlInternalFormat.GlR16F => VkFormat.R16Sfloat,
                GlInternalFormat.GlR32F => VkFormat.R32Sfloat,
                GlInternalFormat.GlRg16F => VkFormat.R16G16Sfloat,
                GlInternalFormat.GlRg32F => VkFormat.R32G32Sfloat,
                GlInternalFormat.GlRgba32F => VkFormat.R32G32B32A32Sfloat,
                GlInternalFormat.GlRgba16F => VkFormat.R16G16B16A16Sfloat,
                GlInternalFormat.GlR8Ui => VkFormat.R8Uint,
                GlInternalFormat.GlR8I => VkFormat.R8Sint,
                GlInternalFormat.GlR16 => VkFormat.R16Unorm,
                GlInternalFormat.GlR16I => VkFormat.R16Sint,
                GlInternalFormat.GlR16Ui => VkFormat.R16Uint,
                GlInternalFormat.GlR32I => VkFormat.R32Sint,
                GlInternalFormat.GlR32Ui => VkFormat.R32Uint,
                GlInternalFormat.GlRg8I => VkFormat.R8G8Sint,
                GlInternalFormat.GlRg8Ui => VkFormat.R8G8Uint,
                GlInternalFormat.GlRg16I => VkFormat.R16G16Sint,
                GlInternalFormat.GlRg16Ui => VkFormat.R16G16Uint,
                GlInternalFormat.GlRg32I => VkFormat.R32G32Sint,
                GlInternalFormat.GlRg32Ui => VkFormat.R32G32Uint,
                GlInternalFormat.GlRgb8 => VkFormat.R8G8B8Unorm,
                GlInternalFormat.GlRgb8I => VkFormat.R8G8B8Sint,
                GlInternalFormat.GlRgb8Ui => VkFormat.R8G8B8Uint,
                GlInternalFormat.GlRgba12 => VkFormat.R12X4G12X4B12X4A12X4Unorm4Pack16,
                GlInternalFormat.GlRgba2 => VkFormat.R14X2G14X2B14X2A14X2Unorm4Pack16ARM,
                GlInternalFormat.GlRgba8I => VkFormat.R8G8B8A8Sint,
                GlInternalFormat.GlRgba8Ui => VkFormat.R8G8B8A8Uint,
                GlInternalFormat.GlRgba16I => VkFormat.R16G16B16A16Sint,
                GlInternalFormat.GlRgba16Ui => VkFormat.R16G16B16A16Uint,
                GlInternalFormat.GlRgba32I => VkFormat.R32G32B32A32Sint,
                GlInternalFormat.GlRgba32Ui => VkFormat.R32G32B32A32Uint,
                GlInternalFormat.GlR8Snorm => VkFormat.R8Snorm,
                GlInternalFormat.GlRg8Snorm => VkFormat.R8G8Snorm,
                GlInternalFormat.GlRgb8Snorm => VkFormat.R8G8B8Snorm,
                GlInternalFormat.GlRgba8Snorm => VkFormat.R8G8B8A8Snorm,
                GlInternalFormat.GlR16Snorm => VkFormat.R16Snorm,
                GlInternalFormat.GlRg16Snorm => VkFormat.R16G16Snorm,
                GlInternalFormat.GlRgb16Snorm => VkFormat.R16G16B16Snorm,
                GlInternalFormat.GlRgba16Snorm => VkFormat.R16G16B16A16Snorm,
                GlInternalFormat.GlRgb10A2 => VkFormat.A2R10G10B10UnormPack32,
                GlInternalFormat.GlRgb10A2Ui => VkFormat.A2R10G10B10UintPack32,
                GlInternalFormat.GlRgb16 => VkFormat.R16G16B16Unorm,
                GlInternalFormat.GlRgb16F => VkFormat.R16G16B16Sfloat,
                GlInternalFormat.GlRgb16I => VkFormat.R16G16B16Sint,
                GlInternalFormat.GlRgb16Ui => VkFormat.R16G16B16Uint,
                GlInternalFormat.GlRgb32F => VkFormat.R32G32B32Sfloat,
                GlInternalFormat.GlRgb32I => VkFormat.R32G32B32Sint,
                GlInternalFormat.GlRgb32Ui => VkFormat.R32G32B32Uint,
                // apple??
                GlInternalFormat.GlBgra8Extension => VkFormat.B8G8R8A8Unorm,
                // BCn
                GlInternalFormat.GlCompressedRgbS3TcDxt1Ext => VkFormat.Bc1RgbUnormBlock, // BC1
                GlInternalFormat.GlCompressedSrgbS3TcDxt1Ext => VkFormat.Bc1RgbSrgbBlock, // BC1
                GlInternalFormat.GlCompressedRgbaS3TcDxt1Ext => VkFormat.Bc1RgbaUnormBlock, // BC1
                GlInternalFormat.GlCompressedSrgbAlphaS3TcDxt1Ext => VkFormat.Bc1RgbaSrgbBlock, // BC1
                GlInternalFormat.GlCompressedRgbaS3TcDxt3Ext => VkFormat.Bc2UnormBlock, // BC2
                GlInternalFormat.GlCompressedSrgbAlphaS3TcDxt3Ext => VkFormat.Bc2SrgbBlock, // BC2
                GlInternalFormat.GlCompressedRgbaS3TcDxt5Ext => VkFormat.Bc3UnormBlock, // BC3
                GlInternalFormat.GlCompressedSrgbAlphaS3TcDxt5Ext => VkFormat.Bc3SrgbBlock, // BC3
                GlInternalFormat.GlCompressedRedGreenRgtc2Ext => VkFormat.Bc5UnormBlock, // BC5
                GlInternalFormat.GlCompressedRedRgtc1Ext => VkFormat.Bc4UnormBlock, // BC4
                GlInternalFormat.GlCompressedSignedRedGreenRgtc2Ext => VkFormat.Bc5SnormBlock, //  BC5
                GlInternalFormat.GlCompressedSignedRedRgtc1Ext => VkFormat.Bc4SnormBlock, // BC4
                GlInternalFormat.GlCompressedRgbBptcSignedFloatArb => VkFormat.Bc6hSfloatBlock, // BC6 Sfloat
                GlInternalFormat.GlCompressedRgbBptcUnsignedFloatArb => VkFormat.Bc6hUfloatBlock, // BC6 Ufloat
                GlInternalFormat.GlCompressedRgbaBptcUnormArb => VkFormat.Bc7UnormBlock, // BC7 rgba Unorm
                GlInternalFormat.GlCompressedSrgbAlphaBptcUnormArb => VkFormat.Bc7SrgbBlock, // BC7 SRGBa

                // Depth/Stencil
                GlInternalFormat.GlDepthComponent16 => VkFormat.D16Unorm,
                GlInternalFormat.GlDepthComponent24 => VkFormat.X8D24UnormPack32,
                GlInternalFormat.GlDepthComponent32F => VkFormat.D32Sfloat,
                GlInternalFormat.GlStencilIndex8 => VkFormat.S8Uint,
                GlInternalFormat.GlDepth24Stencil8 => VkFormat.D24UnormS8Uint,
                GlInternalFormat.GlDepth32FStencil8 => VkFormat.D32SfloatS8Uint,

                // ATC
                GlInternalFormat.GlCompressedRgbAtc => throw new NotImplementedException("Format not supported by Vulkan"),
                GlInternalFormat.GlCompressedRgbaAtcExplicitAlpha => throw new NotImplementedException("Format not supported by Vulkan"),
                GlInternalFormat.GlCompressedRgbaAtcInterpolatedAlpha => throw new NotImplementedException("Format not supported by Vulkan"),

                // Eac
                GlInternalFormat.GlCompressedR11Eac => VkFormat.EacR11UnormBlock,
                GlInternalFormat.GlCompressedSignedR11Eac => VkFormat.EacR11SnormBlock,
                GlInternalFormat.GlCompressedRg11Eac => VkFormat.EacR11G11UnormBlock,
                GlInternalFormat.GlCompressedSignedRg11Eac => VkFormat.EacR11G11SnormBlock,

                // ETC2
                GlInternalFormat.GlCompressedRgb8Etc2 => VkFormat.Etc2R8G8B8UnormBlock,
                GlInternalFormat.GlCompressedSrgb8Etc2 => VkFormat.Etc2R8G8B8SrgbBlock,
                GlInternalFormat.GlCompressedRgb8PunchthroughAlpha1Etc2 => VkFormat.Etc2R8G8B8A1UnormBlock,
                GlInternalFormat.GlCompressedSrgb8PunchthroughAlpha1Etc2 => VkFormat.Etc2R8G8B8A1SrgbBlock,
                GlInternalFormat.GlCompressedRgba8Etc2Eac => VkFormat.Etc2R8G8B8A8UnormBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Etc2Eac => VkFormat.Etc2R8G8B8A8SrgbBlock,

                // Astc Unorm??
                GlInternalFormat.GlCompressedRgbaAstc4X4Khr => VkFormat.Astc4x4UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc5X4Khr => VkFormat.Astc5x4UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc5X5Khr => VkFormat.Astc5x5UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc6X5Khr => VkFormat.Astc6x5UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc6X6Khr => VkFormat.Astc6x6UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc8X5Khr => VkFormat.Astc8x5UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc8X6Khr => VkFormat.Astc8x6UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc8X8Khr => VkFormat.Astc8x8UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc10X5Khr => VkFormat.Astc10x5UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc10X6Khr => VkFormat.Astc10x6UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc10X8Khr => VkFormat.Astc10x8UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc10X10Khr => VkFormat.Astc10x10UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc12X10Khr => VkFormat.Astc12x10UnormBlock,
                GlInternalFormat.GlCompressedRgbaAstc12X12Khr => VkFormat.Astc12x12UnormBlock,

                // Astc sRGB
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc4X4Khr => VkFormat.Astc4x4SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc5X4Khr => VkFormat.Astc5x4SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc5X5Khr => VkFormat.Astc5x5SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc6X5Khr => VkFormat.Astc6x5SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc6X6Khr => VkFormat.Astc6x6SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc8X5Khr => VkFormat.Astc8x5SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc8X6Khr => VkFormat.Astc8x6SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc8X8Khr => VkFormat.Astc8x8SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc10X5Khr => VkFormat.Astc10x5SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc10X6Khr => VkFormat.Astc10x6SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc10X8Khr => VkFormat.Astc10x8SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc10X10Khr => VkFormat.Astc10x10SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc12X10Khr => VkFormat.Astc12x10SrgbBlock,
                GlInternalFormat.GlCompressedSrgb8Alpha8Astc12X12Khr => VkFormat.Astc12x12SrgbBlock,
                _ => throw new NotImplementedException("Format not supported by VECS"),
            };
        }

        public static VkFormat GetVkFormat(this DxgiFormat DxgiFormat)
        {
            return DxgiFormat switch
            {
                DxgiFormat.DxgiFormatUnknown => VkFormat.Undefined,
                //DxgiFormat.DxgiFormatR32G32B32A32Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR32G32B32A32Float => VkFormat.R32G32B32A32Sfloat,
                DxgiFormat.DxgiFormatR32G32B32A32Uint => VkFormat.R32G32B32A32Uint,
                DxgiFormat.DxgiFormatR32G32B32A32Sint => VkFormat.R32G32B32A32Sint,
                //DxgiFormat.DxgiFormatR32G32B32Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR32G32B32Float => VkFormat.R32G32B32Sfloat,
                DxgiFormat.DxgiFormatR32G32B32Uint => VkFormat.R32G32B32Uint,
                DxgiFormat.DxgiFormatR32G32B32Sint => VkFormat.R32G32B32Sint,
                //DxgiFormat.DxgiFormatR16G16B16A16Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR16G16B16A16Float => VkFormat.R16G16B16A16Sfloat,
                DxgiFormat.DxgiFormatR16G16B16A16Unorm => VkFormat.R16G16B16A16Unorm,
                DxgiFormat.DxgiFormatR16G16B16A16Uint => VkFormat.R16G16B16A16Uint,
                DxgiFormat.DxgiFormatR16G16B16A16Snorm => VkFormat.R16G16B16A16Snorm,
                DxgiFormat.DxgiFormatR16G16B16A16Sint => VkFormat.R16G16B16A16Sint,
                //DxgiFormat.DxgiFormatR32G32Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR32G32Float =>VkFormat.R32G32Sfloat,
                DxgiFormat.DxgiFormatR32G32Uint => VkFormat.R32G32Uint,
                DxgiFormat.DxgiFormatR32G32Sint => VkFormat.R32G32Sint,
                //DxgiFormat.DxgiFormatR32G8X24Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatD32FloatS8X24Uint => VkFormat.D32SfloatS8Uint,
                //DxgiFormat.DxgiFormatR32FloatX8X24Typeless => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatX32TypelessG8X24Uint => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR10G10B10A2Typeless => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR10G10B10A2Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR10G10B10A2Uint => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR11G11B10Float => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR8G8B8A8Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR8G8B8A8Unorm => VkFormat.R8G8B8A8Unorm,
                DxgiFormat.DxgiFormatR8G8B8A8UnormSrgb => VkFormat.R8G8B8A8Srgb,
                DxgiFormat.DxgiFormatR8G8B8A8Uint => VkFormat.R8G8B8A8Uint,
                DxgiFormat.DxgiFormatR8G8B8A8Snorm => VkFormat.R8G8B8A8Snorm,
                DxgiFormat.DxgiFormatR8G8B8A8Sint => VkFormat.R8G8B8A8Sint,
                //DxgiFormat.DxgiFormatR16G16Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR16G16Float => VkFormat.R16G16Sfloat,
                DxgiFormat.DxgiFormatR16G16Unorm => VkFormat.R16G16Unorm,
                DxgiFormat.DxgiFormatR16G16Uint => VkFormat.R16G16Uint,
                DxgiFormat.DxgiFormatR16G16Snorm => VkFormat.R16G16Snorm,
                DxgiFormat.DxgiFormatR16G16Sint => VkFormat.R16G16Sint,
                //DxgiFormat.DxgiFormatR32Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatD32Float => VkFormat.D32Sfloat,
                DxgiFormat.DxgiFormatR32Float => VkFormat.R32Sfloat,
                DxgiFormat.DxgiFormatR32Uint => VkFormat.R32Uint,
                DxgiFormat.DxgiFormatR32Sint => VkFormat.R32Sint,
                //DxgiFormat.DxgiFormatR24G8Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatD24UnormS8Uint => VkFormat.D32SfloatS8Uint,
                //DxgiFormat.DxgiFormatR24UnormX8Typeless => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatX24TypelessG8Uint => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR8G8Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR8G8Unorm => VkFormat.R8G8Unorm,
                DxgiFormat.DxgiFormatR8G8Uint => VkFormat.R8G8Uint,
                DxgiFormat.DxgiFormatR8G8Snorm => VkFormat.R8G8Snorm,
                DxgiFormat.DxgiFormatR8G8Sint => VkFormat.R8G8Sint,
                //DxgiFormat.DxgiFormatR16Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR16Float => VkFormat.R16Sfloat,
                DxgiFormat.DxgiFormatD16Unorm => VkFormat.D16Unorm,
                DxgiFormat.DxgiFormatR16Unorm => VkFormat.R16Unorm,
                DxgiFormat.DxgiFormatR16Uint => VkFormat.R16Uint,
                DxgiFormat.DxgiFormatR16Snorm => VkFormat.R16Snorm,
                DxgiFormat.DxgiFormatR16Sint => VkFormat.R16Sint,
                //DxgiFormat.DxgiFormatR8Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatR8Unorm => VkFormat.R8Unorm,
                DxgiFormat.DxgiFormatR8Uint =>  VkFormat.R8Uint,
                DxgiFormat.DxgiFormatR8Snorm => VkFormat.R8Snorm,
                DxgiFormat.DxgiFormatR8Sint =>  VkFormat.R8Sint,
                //DxgiFormat.DxgiFormatA8Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR1Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR9G9B9E5Sharedexp => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR8G8B8G8Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatG8R8G8B8Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatBc1Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc1Unorm => VkFormat.Bc1RgbaUnormBlock,
                DxgiFormat.DxgiFormatBc1UnormSrgb => VkFormat.Bc1RgbaSrgbBlock,
                //DxgiFormat.DxgiFormatBc2Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc2Unorm => VkFormat.Bc2UnormBlock,
                DxgiFormat.DxgiFormatBc2UnormSrgb => VkFormat.Bc2SrgbBlock,
                //DxgiFormat.DxgiFormatBc3Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc3Unorm => VkFormat.Bc3UnormBlock,
                DxgiFormat.DxgiFormatBc3UnormSrgb => VkFormat.Bc3SrgbBlock,
                //DxgiFormat.DxgiFormatBc4Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc4Unorm => VkFormat.Bc4UnormBlock,
                DxgiFormat.DxgiFormatBc4Snorm => VkFormat.Bc4SnormBlock,
                //DxgiFormat.DxgiFormatBc5Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc5Unorm => VkFormat.Bc5UnormBlock,
                DxgiFormat.DxgiFormatBc5Snorm => VkFormat.Bc5SnormBlock,
                DxgiFormat.DxgiFormatB5G6R5Unorm => VkFormat.B5G6R5UnormPack16,
                DxgiFormat.DxgiFormatB5G5R5A1Unorm => VkFormat.B5G5R5A1UnormPack16,
                DxgiFormat.DxgiFormatB8G8R8A8Unorm => VkFormat.B8G8R8A8Unorm,
                //DxgiFormat.DxgiFormatB8G8R8X8Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatR10G10B10XrBiasA2Unorm => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatB8G8R8A8Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatB8G8R8A8UnormSrgb => VkFormat.B8G8R8A8Srgb,
                //DxgiFormat.DxgiFormatB8G8R8X8Typeless => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatB8G8R8X8UnormSrgb => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatBc6HTypeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc6HUf16 => VkFormat.Bc6hUfloatBlock,
                DxgiFormat.DxgiFormatBc6HSf16 => VkFormat.Bc6hSfloatBlock,
                //DxgiFormat.DxgiFormatBc7Typeless => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatBc7Unorm => VkFormat.Bc7UnormBlock,
                DxgiFormat.DxgiFormatBc7UnormSrgb => VkFormat.Bc7SrgbBlock,
                //DxgiFormat.DxgiFormatAyuv => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatY410 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatY416 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatNv12 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatP010 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatP016 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormat420Opaque => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatYuy2 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatY210 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatY216 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatNv11 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatAi44 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatIa44 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatP8 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatA8P8 => throw new NotImplementedException(),
                DxgiFormat.DxgiFormatB4G4R4A4Unorm => VkFormat.B4G4R4A4UnormPack16,
                //DxgiFormat.DxgiFormatP208 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatV208 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatV408 => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatForceUint => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatAtcExt => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatAtcExplicitAlphaExt => throw new NotImplementedException(),
                //DxgiFormat.DxgiFormatAtcInterpolatedAlphaExt => throw new NotImplementedException(),
                _ => throw new NotImplementedException(),
            };
        }

        public static PixelFormat GetPixelFormat(this VkFormat format)
        {
            return format switch
            {
                VkFormat.Undefined => throw new NotImplementedException(),
                VkFormat.R4G4UnormPack8 => throw new NotImplementedException(),
                VkFormat.R4G4B4A4UnormPack16 => throw new NotImplementedException(),
                VkFormat.B4G4R4A4UnormPack16 => throw new NotImplementedException(),
                VkFormat.R5G6B5UnormPack16 => throw new NotImplementedException(),
                VkFormat.B5G6R5UnormPack16 => throw new NotImplementedException(),
                VkFormat.R5G5B5A1UnormPack16 => throw new NotImplementedException(),
                VkFormat.B5G5R5A1UnormPack16 => throw new NotImplementedException(),
                VkFormat.A1R5G5B5UnormPack16 => throw new NotImplementedException(),
                VkFormat.R8Unorm => throw new NotImplementedException(),
                VkFormat.R8Snorm => throw new NotImplementedException(),
                VkFormat.R8Uscaled => throw new NotImplementedException(),
                VkFormat.R8Sscaled => throw new NotImplementedException(),
                VkFormat.R8Uint => throw new NotImplementedException(),
                VkFormat.R8Sint => throw new NotImplementedException(),
                VkFormat.R8Srgb => throw new NotImplementedException(),
                VkFormat.R8G8Unorm => throw new NotImplementedException(),
                VkFormat.R8G8Snorm => throw new NotImplementedException(),
                VkFormat.R8G8Uscaled => throw new NotImplementedException(),
                VkFormat.R8G8Sscaled => throw new NotImplementedException(),
                VkFormat.R8G8Uint => throw new NotImplementedException(),
                VkFormat.R8G8Sint => throw new NotImplementedException(),
                VkFormat.R8G8Srgb => throw new NotImplementedException(),
                VkFormat.R8G8B8Unorm => throw new NotImplementedException(),
                VkFormat.R8G8B8Snorm => throw new NotImplementedException(),
                VkFormat.R8G8B8Uscaled => throw new NotImplementedException(),
                VkFormat.R8G8B8Sscaled => throw new NotImplementedException(),
                VkFormat.R8G8B8Uint => throw new NotImplementedException(),
                VkFormat.R8G8B8Sint => throw new NotImplementedException(),
                VkFormat.R8G8B8Srgb => throw new NotImplementedException(),
                VkFormat.B8G8R8Unorm => throw new NotImplementedException(),
                VkFormat.B8G8R8Snorm => throw new NotImplementedException(),
                VkFormat.B8G8R8Uscaled => throw new NotImplementedException(),
                VkFormat.B8G8R8Sscaled => throw new NotImplementedException(),
                VkFormat.B8G8R8Uint => throw new NotImplementedException(),
                VkFormat.B8G8R8Sint => throw new NotImplementedException(),
                VkFormat.B8G8R8Srgb => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Unorm => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Snorm => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Uscaled => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Sscaled => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Uint => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Sint => throw new NotImplementedException(),
                VkFormat.R8G8B8A8Srgb => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Unorm => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Snorm => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Uscaled => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Sscaled => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Uint => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Sint => throw new NotImplementedException(),
                VkFormat.B8G8R8A8Srgb => throw new NotImplementedException(),
                VkFormat.A8B8G8R8UnormPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8SnormPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8UscaledPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8SscaledPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8UintPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8SintPack32 => throw new NotImplementedException(),
                VkFormat.A8B8G8R8SrgbPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10UnormPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10SnormPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10UscaledPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10SscaledPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10UintPack32 => throw new NotImplementedException(),
                VkFormat.A2R10G10B10SintPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10UnormPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10SnormPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10UscaledPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10SscaledPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10UintPack32 => throw new NotImplementedException(),
                VkFormat.A2B10G10R10SintPack32 => throw new NotImplementedException(),
                VkFormat.R16Unorm => throw new NotImplementedException(),
                VkFormat.R16Snorm => throw new NotImplementedException(),
                VkFormat.R16Uscaled => throw new NotImplementedException(),
                VkFormat.R16Sscaled => throw new NotImplementedException(),
                VkFormat.R16Uint => throw new NotImplementedException(),
                VkFormat.R16Sint => throw new NotImplementedException(),
                VkFormat.R16Sfloat => throw new NotImplementedException(),
                VkFormat.R16G16Unorm => throw new NotImplementedException(),
                VkFormat.R16G16Snorm => throw new NotImplementedException(),
                VkFormat.R16G16Uscaled => throw new NotImplementedException(),
                VkFormat.R16G16Sscaled => throw new NotImplementedException(),
                VkFormat.R16G16Uint => throw new NotImplementedException(),
                VkFormat.R16G16Sint => throw new NotImplementedException(),
                VkFormat.R16G16Sfloat => throw new NotImplementedException(),
                VkFormat.R16G16B16Unorm => throw new NotImplementedException(),
                VkFormat.R16G16B16Snorm => throw new NotImplementedException(),
                VkFormat.R16G16B16Uscaled => throw new NotImplementedException(),
                VkFormat.R16G16B16Sscaled => throw new NotImplementedException(),
                VkFormat.R16G16B16Uint => throw new NotImplementedException(),
                VkFormat.R16G16B16Sint => throw new NotImplementedException(),
                VkFormat.R16G16B16Sfloat => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Unorm => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Snorm => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Uscaled => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Sscaled => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Uint => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Sint => throw new NotImplementedException(),
                VkFormat.R16G16B16A16Sfloat => throw new NotImplementedException(),
                VkFormat.R32Uint => throw new NotImplementedException(),
                VkFormat.R32Sint => throw new NotImplementedException(),
                VkFormat.R32Sfloat => throw new NotImplementedException(),
                VkFormat.R32G32Uint => throw new NotImplementedException(),
                VkFormat.R32G32Sint => throw new NotImplementedException(),
                VkFormat.R32G32Sfloat => throw new NotImplementedException(),
                VkFormat.R32G32B32Uint => throw new NotImplementedException(),
                VkFormat.R32G32B32Sint => throw new NotImplementedException(),
                VkFormat.R32G32B32Sfloat => throw new NotImplementedException(),
                VkFormat.R32G32B32A32Uint => throw new NotImplementedException(),
                VkFormat.R32G32B32A32Sint => throw new NotImplementedException(),
                VkFormat.R32G32B32A32Sfloat => throw new NotImplementedException(),
                VkFormat.R64Uint => throw new NotImplementedException(),
                VkFormat.R64Sint => throw new NotImplementedException(),
                VkFormat.R64Sfloat => throw new NotImplementedException(),
                VkFormat.R64G64Uint => throw new NotImplementedException(),
                VkFormat.R64G64Sint => throw new NotImplementedException(),
                VkFormat.R64G64Sfloat => throw new NotImplementedException(),
                VkFormat.R64G64B64Uint => throw new NotImplementedException(),
                VkFormat.R64G64B64Sint => throw new NotImplementedException(),
                VkFormat.R64G64B64Sfloat => throw new NotImplementedException(),
                VkFormat.R64G64B64A64Uint => throw new NotImplementedException(),
                VkFormat.R64G64B64A64Sint => throw new NotImplementedException(),
                VkFormat.R64G64B64A64Sfloat => throw new NotImplementedException(),
                VkFormat.B10G11R11UfloatPack32 => throw new NotImplementedException(),
                VkFormat.E5B9G9R9UfloatPack32 => throw new NotImplementedException(),
                VkFormat.D16Unorm => throw new NotImplementedException(),
                VkFormat.X8D24UnormPack32 => throw new NotImplementedException(),
                VkFormat.D32Sfloat => throw new NotImplementedException(),
                VkFormat.S8Uint => throw new NotImplementedException(),
                VkFormat.D16UnormS8Uint => throw new NotImplementedException(),
                VkFormat.D24UnormS8Uint => throw new NotImplementedException(),
                VkFormat.D32SfloatS8Uint => throw new NotImplementedException(),
                VkFormat.Bc1RgbUnormBlock => throw new NotImplementedException(),
                VkFormat.Bc1RgbSrgbBlock => throw new NotImplementedException(),
                VkFormat.Bc1RgbaUnormBlock => throw new NotImplementedException(),
                VkFormat.Bc1RgbaSrgbBlock => throw new NotImplementedException(),
                VkFormat.Bc2UnormBlock => throw new NotImplementedException(),
                VkFormat.Bc2SrgbBlock => throw new NotImplementedException(),
                VkFormat.Bc3UnormBlock => throw new NotImplementedException(),
                VkFormat.Bc3SrgbBlock => throw new NotImplementedException(),
                VkFormat.Bc4UnormBlock => throw new NotImplementedException(),
                VkFormat.Bc4SnormBlock => throw new NotImplementedException(),
                VkFormat.Bc5UnormBlock => throw new NotImplementedException(),
                VkFormat.Bc5SnormBlock => throw new NotImplementedException(),
                VkFormat.Bc6hUfloatBlock => throw new NotImplementedException(),
                VkFormat.Bc6hSfloatBlock => throw new NotImplementedException(),
                VkFormat.Bc7UnormBlock => throw new NotImplementedException(),
                VkFormat.Bc7SrgbBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8UnormBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8SrgbBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8A1UnormBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8A1SrgbBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8A8UnormBlock => throw new NotImplementedException(),
                VkFormat.Etc2R8G8B8A8SrgbBlock => throw new NotImplementedException(),
                VkFormat.EacR11UnormBlock => throw new NotImplementedException(),
                VkFormat.EacR11SnormBlock => throw new NotImplementedException(),
                VkFormat.EacR11G11UnormBlock => throw new NotImplementedException(),
                VkFormat.EacR11G11SnormBlock => throw new NotImplementedException(),
                VkFormat.Astc4x4UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc4x4SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc5x4UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc5x4SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc5x5UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc5x5SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc6x5UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc6x5SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc6x6UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc6x6SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc8x5UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc8x5SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc8x6UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc8x6SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc8x8UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc8x8SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc10x5UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc10x5SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc10x6UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc10x6SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc10x8UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc10x8SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc10x10UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc10x10SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc12x10UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc12x10SrgbBlock => throw new NotImplementedException(),
                VkFormat.Astc12x12UnormBlock => throw new NotImplementedException(),
                VkFormat.Astc12x12SrgbBlock => throw new NotImplementedException(),
                VkFormat.G8B8G8R8422Unorm => throw new NotImplementedException(),
                VkFormat.B8G8R8G8422Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R83Plane420Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R82Plane420Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R83Plane422Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R82Plane422Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R83Plane444Unorm => throw new NotImplementedException(),
                VkFormat.R10X6UnormPack16 => throw new NotImplementedException(),
                VkFormat.R10X6G10X6Unorm2Pack16 => throw new NotImplementedException(),
                VkFormat.R10X6G10X6B10X6A10X6Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6G10X6R10X6422Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.B10X6G10X6R10X6G10X6422Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X63Plane420Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X62Plane420Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X63Plane422Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X62Plane422Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X63Plane444Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.R12X4UnormPack16 => throw new NotImplementedException(),
                VkFormat.R12X4G12X4Unorm2Pack16 => throw new NotImplementedException(),
                VkFormat.R12X4G12X4B12X4A12X4Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4G12X4R12X4422Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.B12X4G12X4R12X4G12X4422Unorm4Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X43Plane420Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X42Plane420Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X43Plane422Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X42Plane422Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X43Plane444Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G16B16G16R16422Unorm => throw new NotImplementedException(),
                VkFormat.B16G16R16G16422Unorm => throw new NotImplementedException(),
                VkFormat.G16B16R163Plane420Unorm => throw new NotImplementedException(),
                VkFormat.G16B16R162Plane420Unorm => throw new NotImplementedException(),
                VkFormat.G16B16R163Plane422Unorm => throw new NotImplementedException(),
                VkFormat.G16B16R162Plane422Unorm => throw new NotImplementedException(),
                VkFormat.G16B16R163Plane444Unorm => throw new NotImplementedException(),
                VkFormat.G8B8R82Plane444Unorm => throw new NotImplementedException(),
                VkFormat.G10X6B10X6R10X62Plane444Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G12X4B12X4R12X42Plane444Unorm3Pack16 => throw new NotImplementedException(),
                VkFormat.G16B16R162Plane444Unorm => throw new NotImplementedException(),
                VkFormat.A4R4G4B4UnormPack16 => throw new NotImplementedException(),
                VkFormat.A4B4G4R4UnormPack16 => throw new NotImplementedException(),
                VkFormat.Astc4x4SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc5x4SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc5x5SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc6x5SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc6x6SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc8x5SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc8x6SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc8x8SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc10x5SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc10x6SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc10x8SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc10x10SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc12x10SfloatBlock => throw new NotImplementedException(),
                VkFormat.Astc12x12SfloatBlock => throw new NotImplementedException(),
                VkFormat.A1B5G5R5UnormPack16 => throw new NotImplementedException(),
                VkFormat.A8Unorm => throw new NotImplementedException(),
                VkFormat.PVRTC12BPPUnormBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC14BPPUnormBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC22BPPUnormBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC24BPPUnormBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC12BPPSrgbBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC14BPPSrgbBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC22BPPSrgbBlockImg => throw new NotImplementedException(),
                VkFormat.PVRTC24BPPSrgbBlockImg => throw new NotImplementedException(),
                VkFormat.Astc3x3x3UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc3x3x3SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc3x3x3SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x3x3UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x3x3SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x3x3SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x3UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x3SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x3SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x4UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x4SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc4x4x4SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x4x4UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x4x4SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x4x4SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x4UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x4SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x4SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x5UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x5SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc5x5x5SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x5x5UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x5x5SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x5x5SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x5UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x5SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x5SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x6UnormBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x6SrgbBlockEXT => throw new NotImplementedException(),
                VkFormat.Astc6x6x6SfloatBlockEXT => throw new NotImplementedException(),
                VkFormat.R8BOOLARM => throw new NotImplementedException(),
                VkFormat.R16SfloatFPEncodingBFloat16ARM => throw new NotImplementedException(),
                VkFormat.R8SfloatFPEncodingFloat8e4m3ARM => throw new NotImplementedException(),
                VkFormat.R8SfloatFPEncodingFloat8e5m2ARM => throw new NotImplementedException(),
                VkFormat.R16G16SFixed5NV => throw new NotImplementedException(),
                VkFormat.R10X6UintPack16ARM => throw new NotImplementedException(),
                VkFormat.R10X6G10X6Uint2Pack16ARM => throw new NotImplementedException(),
                VkFormat.R10X6G10X6B10X6A10X6Uint4Pack16ARM => throw new NotImplementedException(),
                VkFormat.R12X4UintPack16ARM => throw new NotImplementedException(),
                VkFormat.R12X4G12X4Uint2Pack16ARM => throw new NotImplementedException(),
                VkFormat.R12X4G12X4B12X4A12X4Uint4Pack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2UintPack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2G14X2Uint2Pack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2G14X2B14X2A14X2Uint4Pack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2UnormPack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2G14X2Unorm2Pack16ARM => throw new NotImplementedException(),
                VkFormat.R14X2G14X2B14X2A14X2Unorm4Pack16ARM => throw new NotImplementedException(),
                VkFormat.G14X2B14X2R14X22Plane420Unorm3Pack16ARM => throw new NotImplementedException(),
                VkFormat.G14X2B14X2R14X22Plane422Unorm3Pack16ARM => throw new NotImplementedException(),
                _ => throw new NotImplementedException(),
            };
        }
    }
}
