#version 460

layout (set = 0, binding = 0) uniform sampler2D srcBloomTexture;
layout (set = 0, binding = 1) uniform sampler2D srcMainTexture;
layout (set = 0, binding = 2) uniform writeonly image2D dstTexture;

layout (set = 0, binding = 3) uniform Constants{
    vec2 outputImageSize;
    float bloomStrength;
} constants;

float inverseLerp(float a, float b, float value)
{
    return a != b ? (value - a) / (b - a) : 0;
}

layout(local_size_x = 8, local_size_y = 8) in;
void main()
{
	uvec2 outPos = gl_GlobalInvocationID.xy;
	if(outPos.x > constants.outputImageSize.x || outPos.y > constants.outputImageSize.y){
        return;
    }
    
    vec2 texCoord = vec2(0);
    vec2 outPosF = vec2(outPos);
    ivec2 outPosI = ivec2(outPos);
    texCoord.x = inverseLerp(0, constants.outputImageSize.x - 1, outPosF.x);
    texCoord.y = inverseLerp(0, constants.outputImageSize.y - 1, outPosF.y);

    vec3 bloom = texture(srcBloomTexture, texCoord).rgb;
    vec3 hdrColour = texture(srcMainTexture, texCoord).rgb;


    imageStore(dstTexture, outPosI, vec4(mix(hdrColour, bloom, vec3(constants.bloomStrength)),1.0));
}