#version 460

layout (set = 0, binding = 0) uniform sampler2D srcTexture;
layout (set = 0, binding = 1) uniform writeonly image2D dstTexture;

layout (set = 0, binding = 2)  uniform Constants{
    vec2 srcResolution;
    vec2 outputImageSize;
} constants;

float inverseLerp(float a, float b, float value)
{
    return a != b ? (value - a) / (b - a) : 0;
}


layout(local_size_x = 8, local_size_y = 8) in;
void main()
{
	uvec2 outPos = gl_GlobalInvocationID.xy;
	if(outPos.x > constants.outputImageSize.x || outPos.y > constants.outputImageSize.y){
        return;
    }
    vec2 texCoord = vec2(0);
    vec2 outPosF = vec2(outPos);
    ivec2 outPosI = ivec2(outPos);
    texCoord.x = inverseLerp(0, constants.outputImageSize.x - 1, outPosF.x);
    texCoord.y = inverseLerp(0, constants.outputImageSize.y - 1, outPosF.y);
    vec2 srcTexelSize = 1.0 / constants.srcResolution;
    float x = srcTexelSize.x;
    float y = srcTexelSize.y;


    // Take 13 samples around current texel:
    // a - b - c
    // - j - k -
    // d - e - f
    // - l - m -
    // g - h - i
    // === ('e' is the current texel) ===
    vec3 a = texture(srcTexture, vec2(texCoord.x - 2*x, texCoord.y + 2*y)).rgb;
    vec3 b = texture(srcTexture, vec2(texCoord.x,       texCoord.y + 2*y)).rgb;
    vec3 c = texture(srcTexture, vec2(texCoord.x + 2*x, texCoord.y + 2*y)).rgb;

    vec3 d = texture(srcTexture, vec2(texCoord.x - 2*x, texCoord.y)).rgb;
    vec3 e = texture(srcTexture, vec2(texCoord.x,       texCoord.y)).rgb;
    vec3 f = texture(srcTexture, vec2(texCoord.x + 2*x, texCoord.y)).rgb;

    vec3 g = texture(srcTexture, vec2(texCoord.x - 2*x, texCoord.y - 2*y)).rgb;
    vec3 h = texture(srcTexture, vec2(texCoord.x,       texCoord.y - 2*y)).rgb;
    vec3 i = texture(srcTexture, vec2(texCoord.x + 2*x, texCoord.y - 2*y)).rgb;

    vec3 j = texture(srcTexture, vec2(texCoord.x - x, texCoord.y + y)).rgb;
    vec3 k = texture(srcTexture, vec2(texCoord.x + x, texCoord.y + y)).rgb;
    vec3 l = texture(srcTexture, vec2(texCoord.x - x, texCoord.y - y)).rgb;
    vec3 m = texture(srcTexture, vec2(texCoord.x + x, texCoord.y - y)).rgb;

    // Apply weighted distribution:
    // 0.5 + 0.125 + 0.125 + 0.125 + 0.125 = 1
    // a,b,d,e * 0.125
    // b,c,e,f * 0.125
    // d,e,g,h * 0.125
    // e,f,h,i * 0.125
    // j,k,l,m * 0.5
    // This shows 5 square areas that are being sampled. But some of them overlap,
    // so to have an energy preserving downsample we need to make some adjustments.
    // The weights are the distributed, so that the sum of j,k,l,m (e.g.)
    // contribute 0.5 to the final color output. The code below is written
    // to effectively yield this sum. We get:
    // 0.125*5 + 0.03125*4 + 0.0625*4 = 1
    vec3 downsample = e*0.125;
    downsample += (a+c+g+i)*0.03125;
    downsample += (b+d+f+h)*0.0625;
    downsample += (j+k+l+m)*0.125;

    imageStore(dstTexture, outPosI, vec4(downsample,1.0));
}