#version 450
#extension GL_KHR_vulkan_glsl: enable
#include "noise3Dgrad.glsl"
#include "structures.glsl"
#include "extra_maths.glsl"
#include "simple_noise_filter.glsl"
#include "rigid_noise_filter.glsl"

layout(set = 0, binding = 0) uniform ComputeShaderParameters{
	uint bufferLength;
	uint width;
	uint height;
	uint depth;
} params;


layout(std430,set = 0, binding = 1) buffer VertexBuffer {
    Vertex vertexBuffer[];
};

layout(set = 0, binding = 2) uniform NoiseGeneratorParams{
	int noiseFilterCount;
	int biomesCount;
	float planetRadius;
	float noiseOffset;
	float noiseStrength;
	float blendAmount;
} noiseParams;

layout(std430, binding = 3) buffer NoiseSettings {
	GlobalNoiseSettings noiseSettings[];
};

layout(std430, binding = 4) buffer Biomes {
	float startHeights[];
} biomes;

layout(std430, binding = 5) buffer ElevationMinMax {
    
	int minElevation;
	int maxElevation;
}minMax;


float evaluate(GlobalNoiseSettings settings, vec3 point){	
	if(settings.filterType == 1){
		return evaluateRigid(settings,point);
	}
	return evaluateSimple(settings,point);
}

float biomePercentFromPoint(vec3 point){
    float heightPercent = (point.y + 1.0) / 2.0;
	heightPercent += (evaluate(noiseSettings[0], point) - noiseParams.noiseOffset) * noiseParams.noiseStrength;
    float biomeIndex = 0;
	int numBiomes = noiseParams.biomesCount;

	float blendRange = noiseParams.blendAmount  / 2.0 + 0.001;

	for(int i = 0; i < numBiomes; i++){
		float dst = heightPercent - biomes.startHeights[i];
		float weight = inverseLerp(-blendRange,blendRange,dst);
        biomeIndex *= (1 - weight);
        biomeIndex += i * weight;
	}

	return biomeIndex / max(1, numBiomes - 1);
}

const float QUANTIIZE_FACTOR = 32768.0;

layout(local_size_x = 2, local_size_y = 1, local_size_z = 1) in;
void main() {
	if(params.width <= gl_GlobalInvocationID.x || params.height <= gl_GlobalInvocationID.y){
	 	return; 
	}
	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y;

	uint bufferIndex = y * params.width + x;

	Vertex v = vertexBuffer[bufferIndex];

	vec3 pos = vec3(v.positionX,v.positionY,v.positionZ);

	
	//v.biome = biomePercentFromPoint(pos);

	float firstLayerValue = 0;
	float unscaledElevation = 0;

	if(noiseParams.noiseFilterCount > 0){
		firstLayerValue = evaluate(noiseSettings[1], pos);
		if(noiseSettings[1].enabled == 1){
			unscaledElevation = firstLayerValue;
		}
	}
	
	for(int i = 2; i < noiseParams.noiseFilterCount+1; i++){
		
		if(noiseSettings[i].enabled == 1){
			float mask = noiseSettings[i].useFirstlayerAsMask == 1 ? firstLayerValue : 1.0;
			unscaledElevation += evaluate(noiseSettings[i], pos)*mask;
		}
	}
	float scaledElevation = noiseParams.planetRadius * (1.0 + max(0,unscaledElevation));

	pos *= scaledElevation;
	v.positionX = pos.x;
	v.positionY = pos.y;
	v.positionZ = pos.z;
	v.elevation = unscaledElevation;
	vertexBuffer[bufferIndex] = v;
	
	float QUANTIIZE_FACTOR = 32768.0;

	int elevationForMinMax = int(unscaledElevation*QUANTIIZE_FACTOR);

	atomicMin(minMax.minElevation,elevationForMinMax);
	atomicMax(minMax.maxElevation,elevationForMinMax);
}