#version 460
#extension GL_ARB_shading_language_include : require


// fucked up float to int conversion magic number (2^16/2)
const float QUANTIIZE_FACTOR = 32768.0;

// vertex buffer to operate on (direct mesh buffer) Only read from here.
layout(std430,set = 0, binding = 0) readonly buffer VertexBuffer {
    float values[];
} vertexBuffer;

// the normal buffer to write into, this is actually the same as the buffer above
// this is interpretened as floats to allow the normalized value to be written
layout(std430,set = 0, binding = 1) writeonly buffer MinMaxBuffer {
    int values[];
} minMaxBuffer;

layout(push_constant) uniform ShaderParams 
{
	uint bufferLength;
	uint width;
	uint height;
	uint depth;
    uint setIndex;
    uint vertexOffset;
} params;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
	if(params.width <= gl_GlobalInvocationID.x || params.height <= gl_GlobalInvocationID.y){
	 	return; 
	}
    uint index = params.vertexOffset + (gl_GlobalInvocationID.y * params.width + gl_GlobalInvocationID.x);

    if(index >= params.vertexOffset + params.bufferLength){
        return;
    }

    index *= 3;

	vec3 pos = vec3(vertexBuffer.values[index], vertexBuffer.values[index + 1], vertexBuffer.values[index + 2]);

	ivec3 ipos = ivec3(pos * QUANTIIZE_FACTOR);

	atomicMin(minMaxBuffer.values[params.setIndex + 0], ipos.x);
	atomicMin(minMaxBuffer.values[params.setIndex + 1], ipos.y);
	atomicMin(minMaxBuffer.values[params.setIndex + 2], ipos.z);

	atomicMax(minMaxBuffer.values[params.setIndex + 3], ipos.x);
	atomicMax(minMaxBuffer.values[params.setIndex + 4], ipos.y);
	atomicMax(minMaxBuffer.values[params.setIndex + 5], ipos.z);

}