#version 460

  
layout (set = 0, binding = 0) uniform sampler2D ssao_Source;
layout (set = 0, binding = 1, r8) uniform writeonly image2D ssao_blur_Source;

layout(push_constant) uniform Constants{
    vec2 outputImageSize;
} constants;


float inverseLerp(float a, float b, float value)
{
    return a != b ? (value - a) / (b - a) : 0;
}

layout(local_size_x = 32, local_size_y = 32) in;
void main() {
	uvec2 outPos = gl_GlobalInvocationID.xy;
	if(outPos.x > constants.outputImageSize.x || outPos.y > constants.outputImageSize.y){
        return;
    }
    vec2 outPosF = vec2(outPos);
    ivec2 outPosI = ivec2(outPos);
    vec2 UV = vec2(0);
    UV.x = inverseLerp(0, constants.outputImageSize.x, outPosF.x);
    UV.y = inverseLerp(0, constants.outputImageSize.y, outPosF.y);

    vec2 texelSize = 1.0 / vec2(textureSize(ssao_Source, 0));
    float result = 0.0;
    for (int x = -2; x < 2; ++x) 
    {
        for (int y = -2; y < 2; ++y) 
        {
            vec2 offset = vec2(float(x), float(y)) * texelSize;
            result += texture(ssao_Source, UV + offset).r;
        }
    }

    imageStore(ssao_blur_Source,outPosI, vec4( result / (4.0 * 4.0)));
}  