<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Planets</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <StartupObject>Planets.Program</StartupObject>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alimer.Bindings.SDL" Version="3.9.8" />
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="TeximpNet" Version="1.4.3" />
    <PackageReference Include="UltralightNet.Binaries" Version="1.3.0" />
    <PackageReference Include="Vortice.Vulkan" Version="2.1.3" />
    <PackageReference Include="Vortice.VulkanMemoryAllocator" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="H:\GitFork\COMP305-2202796\SDL-Vulkan-CS\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="H:\GitFork\COMP305-2202796\SDL-Vulkan-CS\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VECS\VECS.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
	  <RemoveDir Directories="$(TargetDir)/Assets"/>
  </Target>

  

  <Target Name="MakeAssetsDir" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(ProjectDir)/Assets/Shaders;$(SolutionDir)CompiledShaders;$(TargetDir)Assets/Shaders;$(TargetDir)Assets/Models;$(TargetDir)Assets/Textures"/>
  </Target>


  <Target Name="CopyAssets" AfterTargets="MakeAssetsDir">
    
    <ItemGroup>
      <Assets Include="$(SolutionDir)/Assets/**/*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(Assets)"
      DestinationFolder="$(TargetDir)/Assets/%(RecursiveDir)"
     />
  </Target>

  
  <Target Name="CompileShaders" AfterTargets="CopyAssets">

    <ItemGroup>
      <RawShaders Include="$(SolutionDir)/Shaders/**/*.*" Exclude="$(SolutionDir)/Shaders/**/*.glsl" />
    </ItemGroup>

    <Exec Command="$(VULKAN_SDK)/bin/glslc %(RawShaders.Identity) -o $(SolutionDir)/CompiledShaders/%(RawShaders.Filename)%(RawShaders.Extension).spv" />
  </Target>

  <Target Name="CopyShaders" AfterTargets="CompileShaders">
    
    <ItemGroup>
      <Shaders Include="$(SolutionDir)/CompiledShaders/*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(Shaders)"
      DestinationFolder="$(TargetDir)/Assets/Shaders"
     />
  </Target>

</Project>
