#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

struct ObjectBounds {
	vec4 bMin;
	vec4 bMax;
};

struct DrawCommand {
	uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
	uint8_t layerFlags;
};

layout(std140, set = 0, binding = 0) readonly buffer ObjectBoundsBuffer {
	ObjectBounds bounds[];
} boundsBuffer;

layout(set = 0, binding = 1) buffer InstanceBuffer {
	DrawCommand Draws[];
} drawBuffer;

layout(set = 0, binding = 2) uniform sampler2D depthPyramid;

layout(set = 0, binding = 3) uniform CullData{
	vec4 frustum[6]; // data for left/right/top/bottom frustum planes
	mat4 viewMatrix;
	vec2 pyramid;
	float zNear;
	float P00;
	float P11;
	uint drawCount;
	uint8_t includeMask;
	uint8_t excludeMask;
	uint8_t cullMode;
	uint8_t padding;
} cullData;

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
bool projectSphere(vec3 C, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (-C.z < r + znear)
		return false;

	//flip Y because we access depth texture that way
	C.y *= -1.0;
	vec2 cx = C.xz;
	vec2 vx = vec2(sqrt(dot(cx, cx) - r * r), r);
	vec2 minx = mat2(vx.x, vx.y, -vx.y, vx.x) * cx;
	vec2 maxx = mat2(vx.x, -vx.y, vx.y, vx.x) * cx;

	vec2 cy = C.yz;
	vec2 vy = vec2(sqrt(dot(cy, cy) - r * r), r);
	vec2 miny = mat2(vy.x, vy.y, -vy.y, vy.x) * cy;
	vec2 maxy = mat2(vy.x, -vy.y, vy.y, vy.x) * cy;

	aabb = vec4(minx.x / minx.y * P00, miny.x / miny.y * P11, maxx.x / maxx.y * P00, maxy.x / maxy.y * P11);
	aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f); // clip space -> uv space

	return true;
}

bool IsDepthVisible(uint objectIndex){

	ObjectBounds bounds = boundsBuffer.bounds[objectIndex];

	vec4 bmin = bounds.bMin;
	float cullOveride = bmin.w;
	if(cullOveride >= 2) return true;

	vec4 bmax = bounds.bMax;

	vec3 center =  bmin.xyz + ((bmax.xyz - bmin.xyz) * 0.5);

	center = (cullData.viewMatrix * vec4(center, 1.0)).xyz;
	
	float radius = distance(bmin.xyz,bmax.xyz)*0.6;
	
	vec4 aabb;
	if(projectSphere(center, radius, cullData.zNear, cullData.P00, cullData.P11, aabb)){
		
		float width =abs( (aabb.z - aabb.x) * cullData.pyramid.x);
		float height = abs((aabb.w - aabb.y) * cullData.pyramid.y);

		float level = floor(log2(max(width, height)));
		vec2 uv = vec2(aabb.x+aabb.z,abs(aabb.w)+abs(aabb.y))*0.5;
		uv.y = 1.0 - uv.y;
		float depth = textureLod(depthPyramid, uv, 0).x;
		depth = 1.0 - depth;
		depth - 0.1;
		float depthSphere = abs(cullData.zNear / (center.z - radius));

	
		return depthSphere >= depth;
	}
	return true;
}

bool IsVisible(uint objectIndex, int planeCount)
{
	ObjectBounds bounds = boundsBuffer.bounds[objectIndex];

	vec4 bmin = bounds.bMin;
	float cullOveride = bmin.w;
	if(cullOveride > 0.5 && cullOveride < 2) return true;

	vec4 bmax = bounds.bMax;
	bmin.w = 1;
	bmax.w = 1;
	for (int i = 0; i < planeCount; i++)
	{
	    vec4 g = cullData.frustum[i];
	    bool visible =
		dot(g, bmin) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmax.y, bmin.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmax.x, bmin.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, vec4(bmin.x, bmax.y, bmax.z, 1.0)) < 0.0 &&
	    dot(g, bmax) < 0.0;

	    if (visible)
	    {
	        return false;
	    }
	}

	return true;
}

layout(local_size_x = 256) in;
void main()
{
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		uint8_t flags = drawBuffer.Draws[gID].layerFlags;
		
		bool includeMask = (flags | cullData.includeMask) == cullData.includeMask;
		bool excludeMask = (flags | cullData.excludeMask) == cullData.excludeMask;

		bool visible = includeMask && !excludeMask;

		bool fustrumCulling = (uint8_t(1) | cullData.cullMode) == cullData.cullMode;
		bool distanceCulling = (uint8_t(2) | cullData.cullMode) == cullData.cullMode;
		bool depthCulling = (uint8_t(4) | cullData.cullMode) == cullData.cullMode;

		if(visible && fustrumCulling){
			visible = IsVisible(gID, distanceCulling ? 6 : 4);
		}
		if(visible && depthCulling){
			visible = IsDepthVisible(gID);
		}
		
		if(visible){
			drawBuffer.Draws[gID].instanceCount = 1;
		}
		else{
			drawBuffer.Draws[gID].instanceCount = 0;
		}
	}
}