#version 460

layout (set = 0, binding = 0) uniform sampler2D _AOPackedData;
layout (set = 0, binding = 1) uniform writeonly image2D _OcclusionTexture;

layout(set = 0, binding = 2) uniform Constants{
    vec4 _AODepthToViewParams;
    vec4 _ZBufferParams;
    vec4 _AOBufferSize;
    vec4 _FirstTwoDepthMipOffsets;
    vec2 _RTHandleScale;
    float _AOInvRadiusSq;
    float _AORadius;
    float _AOFOVCorrection;
    float _AOMaxRadiusInPixels;
    float _AOInvStepCountPlusOne;
    float _AOSpatialBilateralAggressiveness;
    float _AOIntensity;

    int _AODirectionCount;

	uint _AOStepCount;
	uint cameraIndex;
} constants;

vec2 ClampAndScaleUV (vec2 UV, vec2 texelSize, float numberOfTexels, vec2 scale)
{
	vec2 maxCoord = 1.0f - numberOfTexels * texelSize;
	return min (UV, maxCoord) * scale;
}
vec2 ClampAndScaleUV (vec2 UV, vec2 texelSize, float numberOfTexels)
{
	return ClampAndScaleUV (UV, texelSize, numberOfTexels, constants._RTHandleScale . xy);
}
vec2 ClampAndScaleUVForBilinear (vec2 UV, vec2 texelSize)
{
	return ClampAndScaleUV (UV, texelSize, 0.5f);
}

void UnpackData (float data, out float AO, out float depth)
{
    uint uintData = floatBitsToUint(data);
    vec2 unpacked = unpackHalf2x16(uintData);
	depth = unpacked.x;
	AO = unpacked.y;
}
void UnpackGatheredData (vec4 data, out vec4 AOs, out vec4 depths)
{
	UnpackData (data . x, AOs . x, depths . x);
	UnpackData (data . y, AOs . y, depths . y);
	UnpackData (data . z, AOs . z, depths . z);
	UnpackData (data . w, AOs . w, depths . w);
}
void GatherAOData (sampler2D _AODataSource, vec2 UV, out vec4 AOs, out vec4 depths)
{
	vec4 data = textureGather(_AODataSource, UV);
	UnpackGatheredData (data, AOs, depths);
}

float LinearEyeDepth (float depth, vec4 zBufferParam) {
	return 1.0 / (zBufferParam . z * depth + zBufferParam . w);
}


float BilateralWeight (float sampleDepth, float linearCentralDepth)
{
	float linearSample = LinearEyeDepth (sampleDepth,  constants._ZBufferParams);
	float delta = abs (linearSample - linearCentralDepth);
	float w = clamp (1.0f - ( constants._AOSpatialBilateralAggressiveness * delta + 0.01),0.0,1.0);
	return w;
}

float Blur (vec2 centralPos, out float centralDepth, out float centralAO)
{
	vec4 UnpackedAOs, UnpackedDepths;
	vec2 UV = ClampAndScaleUVForBilinear ((centralPos + vec2 (0.0, 0.0)) * constants._AOBufferSize . zw, constants._AOBufferSize . zw);
	GatherAOData (_AOPackedData, UV, UnpackedAOs, UnpackedDepths);
	centralDepth = UnpackedDepths . y;
	float linearCentralDepth = LinearEyeDepth (centralDepth, constants._ZBufferParams);
	centralAO = UnpackedAOs . y;
	float total = UnpackedAOs . y;
	float totalWeight = 1;
	float weight = BilateralWeight (UnpackedDepths . x, linearCentralDepth);
	total += weight * UnpackedAOs . x;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . z, linearCentralDepth);
	total += weight * UnpackedAOs . z;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . w, linearCentralDepth);
	total += weight * UnpackedAOs . w;
	totalWeight += weight;
	UV = ClampAndScaleUVForBilinear ((centralPos + vec2 (2.0, 0.0)) *  constants._AOBufferSize . zw,  constants._AOBufferSize . zw);
	GatherAOData (_AOPackedData, UV, UnpackedAOs, UnpackedDepths);
	weight = BilateralWeight (UnpackedDepths . x, linearCentralDepth);
	total += weight * UnpackedAOs . x;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . y, linearCentralDepth);
	total += weight * UnpackedAOs . y;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . z, linearCentralDepth);
	total += weight * UnpackedAOs . z;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . w, linearCentralDepth);
	total += weight * UnpackedAOs . w;
	totalWeight += weight;
	UV = ClampAndScaleUVForBilinear ((centralPos + vec2 (0.0, 2.0)) *  constants._AOBufferSize . zw,  constants._AOBufferSize . zw);
	GatherAOData (_AOPackedData, UV, UnpackedAOs, UnpackedDepths);
	weight = BilateralWeight (UnpackedDepths . x, linearCentralDepth);
	total += weight * UnpackedAOs . x;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . y, linearCentralDepth);
	total += weight * UnpackedAOs . y;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . z, linearCentralDepth);
	total += weight * UnpackedAOs . z;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . w, linearCentralDepth);
	total += weight * UnpackedAOs . w;
	totalWeight += weight;
	UV = ClampAndScaleUVForBilinear ((centralPos + vec2 (2.0, 2.0)) *  constants._AOBufferSize . zw,  constants._AOBufferSize . zw);
	GatherAOData (_AOPackedData, UV, UnpackedAOs, UnpackedDepths);
	weight = BilateralWeight (UnpackedDepths . x, linearCentralDepth);
	total += weight * UnpackedAOs . x;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . y, linearCentralDepth);
	total += weight * UnpackedAOs . y;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . z, linearCentralDepth);
	total += weight * UnpackedAOs . z;
	totalWeight += weight;
	weight = BilateralWeight (UnpackedDepths . w, linearCentralDepth);
	total += weight * UnpackedAOs . w;
	totalWeight += weight;
	total /= totalWeight;
	return total;
}
float PositivePow (float base, float power) {return pow (abs (base), power);}
float OutputFinalAO (float AO)
{
	return 1.0f - PositivePow (AO, constants._AOIntensity);
}
void main()
{
	float centralDepth, centralAO;
	float final = Blur (gl_GlobalInvocationID . xy, centralDepth, centralAO);
	imageStore(_OcclusionTexture,ivec2(gl_GlobalInvocationID . xy),vec4( OutputFinalAO (final),0,0,0));
}