#version 460

layout (set = 0, binding = 0) uniform sampler2D _AOPackedData;
layout (set = 0, binding = 1) uniform writeonly image2D _OcclusionTexture;
layout (set = 0, binding = 2) uniform sampler2D mainDepth;

layout(set = 0, binding = 3) uniform Constants{
    vec4 _AODepthToViewParams;
    vec4 _ZBufferParams;
    vec4 _AOBufferSize;
    vec4 _FirstTwoDepthMipOffsets;
    vec4 _ScreenSize;
    vec2 _RTHandleScale;
    float _AOInvRadiusSq;
    float _AORadius;
    float _AOFOVCorrection;
    float _AOMaxRadiusInPixels;
    float _AOInvStepCountPlusOne;
    float _AOSpatialBilateralAggressiveness;
    float _AOIntensity;
    float _StepSize;
    float _BlurTolerance;
    float _UpsampleTolerance;
    float _NoiseFilterStrength;
    int _AODirectionCount;

	uint _AOStepCount;
	uint cameraIndex;

} constants;

shared float DepthCache [256];
shared float AOCache1 [256];
shared float AOCache2 [256];

vec2 ClampAndScaleUV (vec2 UV, vec2 texelSize, float numberOfTexels, vec2 scale)
{
	vec2 maxCoord = 1.0f - numberOfTexels * texelSize;
	return min (UV, maxCoord) * scale;
}
vec2 ClampAndScaleUV (vec2 UV, vec2 texelSize, float numberOfTexels)
{
	return ClampAndScaleUV (UV, texelSize, numberOfTexels, constants._RTHandleScale . xy);
}
vec2 ClampAndScaleUVForBilinear (vec2 UV, vec2 texelSize)
{
	return ClampAndScaleUV (UV, texelSize, 0.5f);
}

void UnpackData (float data, out float AO, out float depth)
{
    uint uintData = floatBitsToUint(data);
    vec2 unpacked = unpackHalf2x16(uintData);
	depth = unpacked.x;
	AO = unpacked.y;
}
void UnpackGatheredData (vec4 data, out vec4 AOs, out vec4 depths)
{
	UnpackData (data . x, AOs . x, depths . x);
	UnpackData (data . y, AOs . y, depths . y);
	UnpackData (data . z, AOs . z, depths . z);
	UnpackData (data . w, AOs . w, depths . w);
}
void GatherAOData (sampler2D _AODataSource, vec2 UV, out vec4 AOs, out vec4 depths)
{
	vec4 data = textureGather(_AODataSource, UV);
	UnpackGatheredData (data, AOs, depths);
}
void PrefetchData (uint index, vec2 uv)
{
	vec4 UnpackedAOs, UnpackedDepths;
	GatherAOData (_AOPackedData, uv, UnpackedAOs, UnpackedDepths);
	AOCache1 [index] = UnpackedAOs . w;
	AOCache1 [index + 1] = UnpackedAOs . z;
	AOCache1 [index + 16] = UnpackedAOs . x;
	AOCache1 [index + 17] = UnpackedAOs . y;
	vec4 ID = 1.0 / UnpackedDepths;
	DepthCache [index] = ID . w;
	DepthCache [index + 1] = ID . z;
	DepthCache [index + 16] = ID . x;
	DepthCache [index + 17] = ID . y;
}

bool CompareDeltas(float d1, float d2, float l1, float l2)
{
    float temp = d1 * d2 + constants._StepSize;
    return temp * temp > l1 * l2 * constants._BlurTolerance;
}
float SmartBlur(float a, float b, float c, float d, float e, bool Left, bool Middle, bool Right)
{
    //b = (Left | Middle) ? b : c;
    b = (Left || Middle) ? b : c;
    a = Left ? a : b;
    //d = (Right | Middle) ? d : c;
    d = (Right || Middle) ? d : c;
    e = Right ? e : d;
    return ((a + e) / 2.0 + b + c + d) / 4.0;
}

void BlurHorizontally (uint leftMostIndex)
{
	float a0 = AOCache1 [leftMostIndex];
	float a1 = AOCache1 [leftMostIndex + 1];
	float a2 = AOCache1 [leftMostIndex + 2];
	float a3 = AOCache1 [leftMostIndex + 3];
	float a4 = AOCache1 [leftMostIndex + 4];
	float a5 = AOCache1 [leftMostIndex + 5];
	float a6 = AOCache1 [leftMostIndex + 6];
	float d0 = DepthCache [leftMostIndex];
	float d1 = DepthCache [leftMostIndex + 1];
	float d2 = DepthCache [leftMostIndex + 2];
	float d3 = DepthCache [leftMostIndex + 3];
	float d4 = DepthCache [leftMostIndex + 4];
	float d5 = DepthCache [leftMostIndex + 5];
	float d6 = DepthCache [leftMostIndex + 6];
	float d01 = d1 - d0;
	float d12 = d2 - d1;
	float d23 = d3 - d2;
	float d34 = d4 - d3;
	float d45 = d5 - d4;
	float d56 = d6 - d5;
	float l01 = d01 * d01 + constants._StepSize;
	float l12 = d12 * d12 + constants._StepSize;
	float l23 = d23 * d23 + constants._StepSize;
	float l34 = d34 * d34 + constants._StepSize;
	float l45 = d45 * d45 + constants._StepSize;
	float l56 = d56 * d56 + constants._StepSize;
	bool c02 = CompareDeltas (d01, d12, l01, l12);
	bool c13 = CompareDeltas (d12, d23, l12, l23);
	bool c24 = CompareDeltas (d23, d34, l23, l34);
	bool c35 = CompareDeltas (d34, d45, l34, l45);
	bool c46 = CompareDeltas (d45, d56, l45, l56);
	AOCache2 [leftMostIndex] = SmartBlur (a0, a1, a2, a3, a4, c02, c13, c24);
	AOCache2 [leftMostIndex + 1] = SmartBlur (a1, a2, a3, a4, a5, c13, c24, c35);
	AOCache2 [leftMostIndex + 2] = SmartBlur (a2, a3, a4, a5, a6, c24, c35, c46);
}

void BlurVertically(uint topMostIndex)
{
    float a0 = AOCache2[topMostIndex];
    float a1 = AOCache2[topMostIndex + 16];
    float a2 = AOCache2[topMostIndex + 32];
    float a3 = AOCache2[topMostIndex + 48];
    float a4 = AOCache2[topMostIndex + 64];
    float a5 = AOCache2[topMostIndex + 80];

    float d0 = DepthCache[topMostIndex + 2];
    float d1 = DepthCache[topMostIndex + 18];
    float d2 = DepthCache[topMostIndex + 34];
    float d3 = DepthCache[topMostIndex + 50];
    float d4 = DepthCache[topMostIndex + 66];
    float d5 = DepthCache[topMostIndex + 82];

    float d01 = d1 - d0;
    float d12 = d2 - d1;
    float d23 = d3 - d2;
    float d34 = d4 - d3;
    float d45 = d5 - d4;

    float l01 = d01 * d01 + constants._StepSize;
    float l12 = d12 * d12 + constants._StepSize;
    float l23 = d23 * d23 + constants._StepSize;
    float l34 = d34 * d34 + constants._StepSize;
    float l45 = d45 * d45 + constants._StepSize;

    bool c02 = CompareDeltas(d01, d12, l01, l12);
    bool c13 = CompareDeltas(d12, d23, l12, l23);
    bool c24 = CompareDeltas(d23, d34, l23, l34);
    bool c35 = CompareDeltas(d34, d45, l34, l45);

    float aoResult1 = SmartBlur(a0, a1, a2, a3, a4, c02, c13, c24);
    float aoResult2 = SmartBlur(a1, a2, a3, a4, a5, c13, c24, c35);

    AOCache1[topMostIndex] = aoResult1;
    AOCache1[topMostIndex + 16] = aoResult2;
}

vec2 ClampAndScaleUVForPoint (vec2 UV)
{
	return min (UV, 1.0f) * constants._RTHandleScale . xy;
}
float PositivePow (float base, float power) {return pow (abs (base), power);}
vec4 OutputFinalAO (float AO)
{
	return vec4(1.0f - PositivePow (AO, constants._AOIntensity),0.0,0.0,0.0);
}
float BilateralUpsample (float HiDepth, vec4 LowDepths, vec4 LowAO)
{
	vec4 weights = vec4 (9, 3, 1, 3) / (abs (HiDepth - LowDepths) + constants._UpsampleTolerance);
	float TotalWeight = dot (weights, vec4(1.0)) + constants._NoiseFilterStrength;
	float WeightedSum = dot (LowAO, weights) + constants._NoiseFilterStrength;
	return WeightedSum / TotalWeight;
}
//SV_GroupIndex       = gl_LocalInvocationIndex
//SV_GroupID          = gl_WorkGroupID
//SV_GroupThreadID    = gl_LocalInvocationID
//SV_DispatchThreadID = gl_GlobalInvocationID
void main() //(uint3 Gid : SV_GroupID, uint GI : SV_GroupIndex, uint3 GTid : SV_GroupThreadID, uint3 DTid : SV_DispatchThreadID)
{
	//unity_StereoEyeIndex = DTid . z;;
    uint GI = gl_LocalInvocationIndex;
    uvec3 Gid = gl_WorkGroupID;
    uvec3 GTid = gl_LocalInvocationID;
    uvec3 DTid = gl_GlobalInvocationID;
	vec2 UV = ClampAndScaleUVForBilinear ((ivec2 (DTid . xy + GTid . xy - 2)) * constants._AOBufferSize . zw, constants._AOBufferSize . zw);
	PrefetchData (GTid . x << 1 | GTid . y << 5, UV);
	//GroupMemoryBarrierWithGroupSync ();
    barrier();
	if (GI < 39)
	BlurHorizontally ((GI / 3) * 16 + (GI % 3) * 3);
	//GroupMemoryBarrierWithGroupSync ();
    barrier();
	if (GI < 45)
	BlurVertically ((GI / 9) * 32 + GI % 9);
	//GroupMemoryBarrierWithGroupSync ();
    barrier();
	uint Idx0 = GTid . x + GTid . y * 16;
	vec4 LoSSAOs = vec4 (AOCache1 [Idx0 + 16], AOCache1 [Idx0 + 17], AOCache1 [Idx0 + 1], AOCache1 [Idx0]);
	vec2 UV0 = ClampAndScaleUVForBilinear (DTid . xy * constants._AOBufferSize . zw, constants._AOBufferSize . zw);
	vec2 UV1 = ClampAndScaleUVForPoint (DTid . xy * 2 * constants._ScreenSize . zw);
	UV1 . y *= 2.0f / 3.0f;
	vec4 highDepth = textureGather(mainDepth, UV1);
	vec4 LowDepth = 1.0 / (vec4 (DepthCache [Idx0 + 16], DepthCache [Idx0 + 17], DepthCache [Idx0 + 1], DepthCache [Idx0]));
	ivec2 OutST = ivec2(DTid . xy << 1);
	imageStore(_OcclusionTexture, (OutST + ivec2 (0, - 1)),  OutputFinalAO (BilateralUpsample (highDepth . z, LowDepth . zwxy, LoSSAOs . zwxy)));
	imageStore(_OcclusionTexture, (OutST),  OutputFinalAO (BilateralUpsample (highDepth . y, LowDepth . yzwx, LoSSAOs . yzwx)));
	imageStore(_OcclusionTexture, (OutST + ivec2 (- 1, - 1)),  OutputFinalAO (BilateralUpsample (highDepth . w, LowDepth . wxyz, LoSSAOs . wxyz)));
	imageStore(_OcclusionTexture, (OutST + ivec2 (- 1, 0)), OutputFinalAO (BilateralUpsample (highDepth . x, LowDepth . xyzw, LoSSAOs . xyzw)));
}