// half res
#version 460
#extension GL_ARB_shading_language_include : require
#include "../../common_structures.glsl"

layout(set = 0,binding = 0) readonly buffer CameraDatas {
	CameraData values[];
} cameraData;

layout (set = 0, binding = 1, RGBA32F) uniform readonly image2D g_NormalsIn;
layout (set = 0, binding = 2, R32f) uniform image2D mainDepth;
layout (set = 0, binding = 3, R32f) uniform writeonly image2D _AOPackedData;

layout(set = 0, binding = 4) uniform Constants{
    vec4 _AODepthToViewParams;
    vec4 _ZBufferParams;
    vec4 _AOBufferSize;
    vec4 _FirstTwoDepthMipOffsets;
    vec2 _RTHandleScale;
    float _AOInvRadiusSq;
    float _AORadius;
    float _AOFOVCorrection;
    float _AOMaxRadiusInPixels;
    float _AOInvStepCountPlusOne;
    float _AOSpatialBilateralAggressiveness;
    float _AOIntensity;

    int _AODirectionCount;

	uint _AOStepCount;
	uint cameraIndex;
} constants;

float GetDepthSample (vec2 positionSS, bool lowerRes) {
	if (lowerRes) {
		return imageLoad(mainDepth , (ivec2 (constants._FirstTwoDepthMipOffsets . zw + uvec2( positionSS . xy / 2)))) . r;
	}
	else {
		return imageLoad(mainDepth ,(ivec2 (constants._FirstTwoDepthMipOffsets . xy + uvec2( positionSS . xy))) ). r;
	}
}


#include "common_functions.glsl"

void main ()
{
	float currDepth = GetDepthForCentral (gl_GlobalInvocationID . xy);
	vec3 positionVS = GetPositionVS (gl_GlobalInvocationID . xy, currDepth);
	vec3 normalBufferData = normalize(imageLoad(g_NormalsIn, (ivec2 (gl_GlobalInvocationID . xy * 2))).rgb);
	float offset = GetOffset (gl_GlobalInvocationID . xy);
	vec2 rayStart = gl_GlobalInvocationID . xy;
	float integral = 0;
	int dirCount = constants._AODirectionCount;
	vec3 V = normalize (- positionVS);
	float fovCorrectedradiusSS = clamp (constants._AORadius * constants._AOFOVCorrection * (1.0/positionVS . z), constants._AOStepCount, constants._AOMaxRadiusInPixels);
	float step = max (1, fovCorrectedradiusSS * constants._AOInvStepCountPlusOne);
	for (int i = 0; i < dirCount; ++ i)
	{
		vec2 dir = GetDirection (gl_GlobalInvocationID . xy, i);
		vec2 negDir = - dir + 1e-30;
		vec2 maxHorizons;
		maxHorizons . x = HorizonLoop (positionVS, V, rayStart, dir, offset, step, 0);
		maxHorizons . y = HorizonLoop (positionVS, V, rayStart, negDir, offset, step, 0);
		vec3 normalVS = GetNormalVS (normalBufferData);
		vec3 sliceN = normalize (cross (vec3 (dir . xy, 0.0f), V . xyz));
		vec3 projN = normalVS - sliceN * dot (normalVS, sliceN);
		float projNLen = length (projN);
		float cosN = dot (projN / projNLen, V);
		vec3 T = cross (V, sliceN);
		float N = - sign (dot (projN, T)) * GTAOFastAcos (cosN);
		maxHorizons . x = - GTAOFastAcos (maxHorizons . x);
		maxHorizons . y = GTAOFastAcos (maxHorizons . y);
		maxHorizons . x = N + max (maxHorizons . x - N, - 1.57079632679489661923);
		maxHorizons . y = N + min (maxHorizons . y - N, 1.57079632679489661923);
		integral += AnyIsNaN (maxHorizons) ? 1 : IntegrateArcCosWeighted (maxHorizons . x, maxHorizons . y, N, cosN);
	}
	integral /= dirCount;
	if (currDepth == (0.0) || integral < - 1e-2f)
	{
		integral = 1;
	}
	imageStore(_AOPackedData, ivec2 (gl_GlobalInvocationID . xy), vec4(PackAOOutput (clamp (integral,0.0,1.0), currDepth),0.0,0.0,0.0));
}