#version 460
#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require
#include "../common_structures.glsl"
#include "../lighting.glsl"
#include "../shadows.glsl"
#include "../pbr/pbr.glsl"

layout(set = 0, binding = 0) uniform LightingInfo {
	int numDirLights;
	int numDirLightsShadows;
	int numPointLights;
	int numPointLightShadows;
	int numSpotLights;
	int numSpotLightShadows;
} lighting;

layout(set = 0, binding = 1) readonly buffer DirectionalLights {
	DirectionalLight values[];
} directionalLightBuffer;

layout (set = 0, binding = 2) readonly buffer PointLights {
	PointLight values[];
} pointLightBuffer;

layout (set = 0, binding = 3) readonly buffer SpotLights {
	SpotLight values[];
} spotLightBuffer;

layout(set = 0,binding = 4) readonly buffer CameraDatas {
	CameraData values[];
} cameraData;

layout (set = 1, binding = 0) uniform sampler2DArray dirShadow;
layout (set = 1, binding = 1) uniform sampler2DArray[] plShadow;
layout (set = 1, binding = 2) uniform sampler2D[] slShadow;

layout (set = 1, binding = 3) uniform samplerCube samplerIrradiance;
layout (set = 1, binding = 4) uniform sampler2D samplerBRDFLUT;
layout (set = 1, binding = 5) uniform samplerCube prefilteredMap;

layout (set = 2, binding = 0, rgba16f) uniform readonly image2D g_PositionIn;
layout (set = 2, binding = 1, rgba16f) uniform readonly image2D g_NormalsIn;
layout (set = 2, binding = 2, rgba8) uniform readonly image2D g_AlbedoIn;
layout (set = 2, binding = 3, rgba8) uniform readonly image2D g_MaskIn;
layout (set = 2, binding = 4, r8) uniform readonly image2D ssao_blur_Source;

layout (set = 2, binding = 5, rgba32f) uniform writeonly image2D outImage;

layout(push_constant) uniform Constants{
    vec2 outputImageSize;	
    float exposure;
    float gamma;
	uint cameraIndex;
} constants;

vec3 plContribution(PointLight pl, vec3 posWorld, vec3 cameraPosWorld, vec3 V, vec3 N, vec3 F0, vec3 albedo, vec2 metalRoughness, int lightIndex, bool hasShadow){
    float distance = length(pl.position.xyz - posWorld);

    if(distance <= pl.farPlane){
        float shadow= hasShadow ? ShadowPlCalculationAlt(plShadow[lightIndex], posWorld, cameraPosWorld, pl) : 1.0;
        vec3 L = normalize(pl.position.xyz - posWorld);
        return specularContribution(L, V, N, F0, albedo, metalRoughness, pl.specular.rgb) * shadow;
        
    }
    return vec3(0.0);
}

vec3 slContribution(SpotLight sl, vec3 posWorld, vec3 cameraPosWorld, vec3 V, vec3 N, vec3 F0, vec3 albedo, vec2 metalRoughness, int lightIndex, bool hasShadow){
    float distance = length(sl.position.xyz - posWorld);
    if(distance <= sl.farPlane) {

        float shadow = hasShadow ? ShadowSlCalculationAlt(slShadow[lightIndex], posWorld, cameraPosWorld, sl) : 1.0;			
        vec3 L = normalize(sl.position.xyz - posWorld);
        return specularContribution(L, V, N, F0,albedo,  metalRoughness, sl.specular.rgb * CalcSpotLightIntensity(sl, posWorld)) * shadow;
    }
    return vec3(0.0);
}

layout(local_size_x = 32, local_size_y = 32) in;
void main(){

	uvec2 outPos = gl_GlobalInvocationID.xy;
	if(outPos.x > constants.outputImageSize.x || outPos.y > constants.outputImageSize.y){
        return;
    }
    vec2 outPosF = vec2(outPos);
    ivec2 outPosI = ivec2(outPos);
    
    vec4 positionWorld = imageLoad(g_PositionIn,outPosI);
    vec3 N = imageLoad(g_NormalsIn,outPosI).rgb;
    
	vec3 cameraPosWorld = cameraData.values[constants.cameraIndex].inverseViewMatrix[3].xyz;    
	vec3 V = normalize(cameraPosWorld - positionWorld.xyz);
	vec3 maskValue = imageLoad(g_MaskIn,outPosI).rga; 
	vec2 metalRoughness = vec2(maskValue.r, 1 - maskValue.b);
    vec3 ambient = maskValue.ggg;
	float AO = imageLoad(ssao_blur_Source,outPosI).r;
	ambient *= AO;
    vec3 albedo = pow(imageLoad(g_AlbedoIn, outPosI).rgb, vec3(2.2));
	vec4 outColour = vec4(ambientComponent(samplerIrradiance, prefilteredMap, samplerBRDFLUT, N, V, albedo, ambient, metalRoughness),1.0);

    vec3 viewPos = (cameraData.values[constants.cameraIndex].viewMatrix *  vec4(positionWorld.xyz,1.0)).xyz;
	int cascadeIndex = 0;
	float shadow= 1.0;
    vec3 Lo = vec3(0);
	vec3 F0 = vec3(0.04); 
	F0 = mix(F0, albedo, metalRoughness.r);
    
    for(int i = 0; i < lighting.numDirLights; i++) {
		DirectionalLight directionalLight = directionalLightBuffer.values[i];
		
		shadow = i < lighting.numDirLightsShadows ? DirShadows(
			dirShadow,
			directionalLight,
			positionWorld.xyz,
			viewPos,
			cascadeIndex) : 1.0;
		Lo += specularContribution(-directionalLight.direction.xyz, V, N, F0, albedo,metalRoughness, directionalLight.specular.rgb)*shadow;
	}
    

    for(int i = 0; i < lighting.numPointLights; i++) {
		PointLight pl = pointLightBuffer.values[i];		
        Lo += plContribution(pl, positionWorld.xyz, cameraPosWorld, V, N, F0, albedo, metalRoughness,i, i < lighting.numPointLightShadows);
    }
    
    for(int i = 0; i < lighting.numSpotLights; i++) {
		SpotLight sl = spotLightBuffer.values[i];		
        Lo += slContribution(sl, positionWorld.xyz, cameraPosWorld, V, N, F0, albedo, metalRoughness,i, i < lighting.numSpotLightShadows);
    }
    outColour.rgb += Lo;


	// Tone mapping
	outColour.rgb = Uncharted2Tonemap(outColour.rgb * constants.exposure);
    
	outColour.rgb = outColour.rgb * (1.0 / Uncharted2Tonemap(vec3(11.2)));

	// Gamma correction
	outColour.rgb = pow(outColour.rgb, vec3(1.0 / constants.gamma));

	imageStore(outImage, outPosI, outColour);
}